from sqlalchemy import String, Integer, ForeignKey, Text, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.models.base import Base


class Project(Base):
    __tablename__ = "projects"

    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"))
    title: Mapped[str] = mapped_column(String(200))
    status: Mapped[str] = mapped_column(String(20), default="draft")
    # draft -> planning -> generating -> composing -> done

    # LLM conversation context
    chat_history: Mapped[dict | None] = mapped_column(JSON, default=list)

    # Style & config
    visual_style: Mapped[str | None] = mapped_column(String(50))
    music_style: Mapped[str | None] = mapped_column(String(50))
    mood: Mapped[str | None] = mapped_column(String(50))
    style_config: Mapped[dict | None] = mapped_column(JSON, default=dict)

    # Storyboard generated by LLM
    storyboard: Mapped[dict | None] = mapped_column(JSON, default=list)

    # Character bank
    character_bank: Mapped[dict | None] = mapped_column(JSON, default=dict)

    # Model preferences (user overrides for model routing)
    model_preferences: Mapped[dict | None] = mapped_column(JSON, default=dict)

    user = relationship("User", back_populates="projects")
    tasks = relationship("Task", back_populates="project", cascade="all, delete-orphan")
    media = relationship("Media", back_populates="project", cascade="all, delete-orphan")


class Task(Base):
    __tablename__ = "tasks"

    project_id: Mapped[int] = mapped_column(ForeignKey("projects.id"))
    type: Mapped[str] = mapped_column(String(20))
    # image / video / music / compose / export
    model_name: Mapped[str | None] = mapped_column(String(50))
    status: Mapped[str] = mapped_column(String(20), default="pending")
    # pending -> running -> completed / failed
    params: Mapped[dict | None] = mapped_column(JSON, default=dict)
    result: Mapped[dict | None] = mapped_column(JSON, default=dict)
    quality_score: Mapped[float | None] = mapped_column(default=None)
    retry_count: Mapped[int] = mapped_column(default=0)
    error_message: Mapped[str | None] = mapped_column(Text)

    project = relationship("Project", back_populates="tasks")
    media = relationship("Media", back_populates="task")


class Media(Base):
    __tablename__ = "media"

    project_id: Mapped[int] = mapped_column(ForeignKey("projects.id"))
    task_id: Mapped[int | None] = mapped_column(ForeignKey("tasks.id"))
    type: Mapped[str] = mapped_column(String(20))
    # image / video / audio / final_video
    file_url: Mapped[str] = mapped_column(String(500))
    duration: Mapped[float | None] = mapped_column(default=None)
    metadata_json: Mapped[dict | None] = mapped_column(JSON, default=dict)
    sort_order: Mapped[int] = mapped_column(default=0)

    project = relationship("Project", back_populates="media")
    task = relationship("Task", back_populates="media")
