from __future__ import annotations

import asyncio
import json
import os
import subprocess
import tempfile
import threading
from pathlib import Path

from fastapi import APIRouter, BackgroundTasks, Query
from pydantic import BaseModel

from app.services.generation_service import GenerationService
from app.utils.storage import upload_file

router = APIRouter(prefix="/home", tags=["home"])

_CACHE_PATH = Path(__file__).resolve().parents[2] / "local_storage" / "home_veo_gallery.json"
_CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
_GEN_LOCK = threading.Lock()

_DEFAULT_ITEMS = [
    {
        "key": "kpop",
        "title": "K-Pop Visual Edit",
        "artist": "Cyberpunk style",
        "tag": "K-Pop",
        "prompt": "Neon rooftop dance scene, high-energy camera movement, cyberpunk lights",
        "cover": "https://picsum.photos/seed/aimv-veo-kpop-neon/1280/720",
    },
    {
        "key": "guofeng",
        "title": "Chinese Classical",
        "artist": "Traditional ink",
        "tag": "国风",
        "prompt": "Chinese classical courtyard, ink-wash atmosphere, cinematic dolly shot",
        "cover": "https://picsum.photos/seed/aimv-veo-guofeng-mist/1280/720",
    },
    {
        "key": "indie",
        "title": "Indie Film Aesthetic",
        "artist": "Golden hour",
        "tag": "Indie",
        "prompt": "Golden-hour street portrait, handheld film texture, emotional close-up",
        "cover": "https://picsum.photos/seed/aimv-veo-indie-goldenhour/1280/720",
    },
    {
        "key": "edm",
        "title": "Electronic Dance",
        "artist": "Neon club scene",
        "tag": "EDM",
        "prompt": "Night club wide shot, laser beams and haze, beat-synced movement",
        "cover": "https://picsum.photos/seed/aimv-veo-edm-club/1280/720",
    },
    {
        "key": "rnb",
        "title": "Urban R&B",
        "artist": "Street photography",
        "tag": "R&B",
        "prompt": "Urban night alley, soft backlight portrait, smooth cinematic pan",
        "cover": "https://picsum.photos/seed/aimv-veo-rnb-urban/1280/720",
    },
    {
        "key": "epic",
        "title": "Fantasy Epic",
        "artist": "Cinematic orchestral",
        "tag": "Epic",
        "prompt": "Epic fantasy valley, volumetric light and fog, heroic wide composition",
        "cover": "https://picsum.photos/seed/aimv-veo-epic-fantasy/1280/720",
    },
]


class HomeGalleryItem(BaseModel):
    key: str
    title: str
    artist: str
    tag: str
    prompt: str
    cover: str
    generated_by: str = "mock"


class HomeGalleryResponse(BaseModel):
    generating: bool
    items: list[HomeGalleryItem]


def _load_cache() -> dict:
    if not _CACHE_PATH.exists():
        return {}
    try:
        return json.loads(_CACHE_PATH.read_text())
    except Exception:
        return {}


def _save_cache(data: dict) -> None:
    _CACHE_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2))


def _extract_cover_frame(video_url: str) -> str:
    fd, output = tempfile.mkstemp(suffix=".jpg")
    os.close(fd)
    try:
        subprocess.run(
            [
                "ffmpeg", "-y",
                "-ss", "0.5",
                "-i", video_url,
                "-vframes", "1",
                "-q:v", "2",
                output,
            ],
            check=True,
            capture_output=True,
        )
        return output
    except Exception:
        try:
            os.unlink(output)
        except OSError:
            pass
        return ""


def _build_items_from_cache(cache: dict) -> list[HomeGalleryItem]:
    items: list[HomeGalleryItem] = []
    for x in _DEFAULT_ITEMS:
        c = cache.get(x["key"], {})
        items.append(
            HomeGalleryItem(
                key=x["key"],
                title=x["title"],
                artist=x["artist"],
                tag=x["tag"],
                prompt=x["prompt"],
                cover=c.get("cover") or x["cover"],
                generated_by=c.get("generated_by") or "mock",
            )
        )
    return items


def _generate_missing_covers() -> None:
    if not _GEN_LOCK.acquire(blocking=False):
        return
    try:
        cache = _load_cache()
        service = GenerationService()
        for item in _DEFAULT_ITEMS:
            key = item["key"]
            # Skip entries already generated by Veo.
            if (cache.get(key) or {}).get("generated_by") == "veo":
                continue
            try:
                result = asyncio.run(
                    service.generate_video(
                        prompt=item["prompt"],
                        model_name="veo-3.1-fast",
                        params={"duration": 3},
                    )
                )
                frame_path = _extract_cover_frame(result.file_url)
                if not frame_path:
                    raise RuntimeError("failed to extract frame")
                try:
                    cover_url = upload_file(frame_path, "image/jpeg")
                finally:
                    try:
                        os.unlink(frame_path)
                    except OSError:
                        pass
                cache[key] = {"cover": cover_url, "generated_by": "veo"}
                _save_cache(cache)
            except Exception:
                # Keep default mock cover on failure; continue with next item.
                continue
    finally:
        _GEN_LOCK.release()


@router.get("/veo-gallery", response_model=HomeGalleryResponse)
async def get_home_veo_gallery(
    background_tasks: BackgroundTasks,
    trigger: bool = Query(True),
):
    cache = _load_cache()
    if trigger:
        background_tasks.add_task(_generate_missing_covers)
    return HomeGalleryResponse(
        generating=_GEN_LOCK.locked(),
        items=_build_items_from_cache(cache),
    )

