<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import { useLangStore } from '@/stores/lang'
import { storeToRefs } from 'pinia'

const router = useRouter()

// ─── i18n ────────────────────────────────────────────────────────────────────
const langStore = useLangStore()
const { lang } = storeToRefs(langStore)

const i18n = {
  en: {
    nav_gallery: 'Gallery', nav_create: 'Create', nav_signin: 'Sign In',
    lang_label: '语言 / Language', lang_current: 'EN',
    hero_title: 'The synthesizer for the music video world.',
    hero_subtitle: 'Multi-agent AI orchestration — from lyrics to final MV, in minutes.',
    hero_cta: 'Start creating now',
    hero_trusted: 'Used by 500+ creators in beta',
    hero_quote: '"AIMV Studio turned my concept into a full MV in under 20 minutes." — Beta User',
    stats_clips: 'AI clips generated', stats_projects: 'Projects created', stats_models: 'AI models integrated',
    music_videos_title: 'Music videos',
    ai_gen_title: 'AI-Generated Scenes',
    ai_gen_desc: 'Describe your vision and the Screenwriter Agent builds a shot-by-shot storyboard. Images and video clips are generated by Z-image, Wan2.2, and other top models. No shooting required.',
    multi_model_title: 'Multi-Model Pipeline',
    multi_model_desc: 'Switch between Seedance 2.0, Veo 3.1, Grok Video 1.0, and Wan2.2 14B per shot — or let the Director Agent decide.',
    multi_model_note: 'AIMV Studio feels like a professional NLE, but the entire timeline is written by AI.',
    pipeline_title: 'Agent Collaboration Pipeline',
    pipeline_subtitle: 'Four specialized AI Agents work in sequence to turn a description into a finished MV',
    pipeline_note: 'Each Agent communicates via structured JSON. The Verifier closes the quality loop with automatic retry.',
    music_demo_title: 'Music Analysis Engine',
    music_demo_subtitle: 'BPM detection · structure segmentation · lyrics transcription — all driving the video generation',
    music_demo_bpm: 'BPM',
    models_title: 'AI Model Matrix',
    models_subtitle: 'Choose per-shot, or let the Director Agent route automatically',
    models_tab_image: 'Image', models_tab_video: 'Video', models_tab_music: 'Music',
    model_open: 'Open Source', model_commercial: 'Commercial',
    export_title: 'Multi-Platform Export',
    export_subtitle: 'One-click export with loudness normalization (−14 LUFS / EBU R128) and SRT subtitle burn-in',
    testimonials_title: 'What creators say',
    testimonials_subtitle: 'Creators in beta have produced over 10,000 AI-generated video clips with AIMV Studio.',
    t1_name: 'Lin Wei',       t1_role: 'Indie Music Producer',
    t1_quote: 'AIMV Studio understood my style from just a few sentences. The storyboard nailed the mood and the generated shots needed zero retouching.',
    t2_name: 'Zhao Ming',     t2_role: 'Music Video Director',
    t2_quote: 'The multi-agent pipeline is genuinely impressive. I briefed it like I would a human team, and it delivered exactly what I envisioned.',
    t3_name: 'Sara K.',       t3_role: 'Electronic Artist',
    t3_quote: "I've tried every AI video tool. AIMV Studio is the only one that truly treats the music as the real driver of the visuals.",
    t4_name: 'Chen Jie',      t4_role: 'Singer-Songwriter',
    t4_quote: 'The BPM-synced cuts and automatic loudness normalization to −14 LUFS saved me hours of post-production.',
    t5_name: 'Alex Turner',   t5_role: 'Visual Artist & Director',
    t5_quote: 'Character consistency across 20+ shots was something I thought would break any AI. AIMV Studio held up perfectly.',
    t6_name: 'Wang Fang',     t6_role: 'Content Creator',
    t6_quote: 'From a single description to a fully exported MV in just 18 minutes. I was genuinely shocked by the quality.',
    what_you_create_title: 'What you could create',
    what_you_create_subtitle: 'AI-generated music videos with unlimited style variety.',
    news_title: 'News & Updates',
    news_1: 'AIMV Studio 1.0: Full multi-agent MV generation pipeline now available',
    news_2: 'Wan2.2 14B integration: Open-source 4K video generation with Apache 2.0 license',
    news_3: 'Real audio segmentation: MFCC + agglomerative clustering for beat-perfect video cuts',
    news_date_1: '2025/03/15', news_date_2: '2025/02/28', news_date_3: '2025/01/20',
    faq_title: 'Frequently asked questions',
    faq_1_q: 'What is AIMV Studio?',
    faq_1_a: 'AIMV Studio is an AI music video platform. Four specialized agents — Screenwriter, Director, Music Producer, Verifier — collaborate to plan, generate, and review every shot.',
    faq_2_q: 'Who owns the generated videos?',
    faq_2_a: 'You have complete ownership. We claim zero rights and never use your content without explicit permission.',
    faq_3_q: 'Which AI models are supported?',
    faq_3_a: 'Z-image for images; Wan2.2 14B, Seedance 2.0, Veo 3.1, Grok Video 1.0 for video; ACEStep 1.5, Suno, Google Lyria for music.',
    faq_4_q: 'How does music analysis work?',
    faq_4_a: 'librosa for BPM/beat detection, MFCC + chroma + agglomerative clustering for structure segmentation, faster-whisper for lyrics transcription.',
    footer_tagline: 'Built by students who love AI and music. Open-source, community-driven.',
    footer_product: 'Product', footer_p1: 'Create',    footer_p2: 'Gallery', footer_p3: 'My Projects', footer_p4: 'API Docs',
    footer_models: 'AI Models', footer_m1: 'Z-image', footer_m2: 'Wan2.2 14B', footer_m3: 'Seedance 2.0', footer_m4: 'ACEStep 1.5',
    footer_more: 'More', footer_more1: 'GitHub', footer_more2: 'Docs', footer_more3: 'About', footer_more4: 'Open Source',
    footer_socials: 'Community', footer_s1: 'GitHub', footer_s2: 'Discord', footer_s3: 'Bilibili', footer_s4: 'Twitter / X',
  },
  zh: {
    nav_gallery: '作品库', nav_create: '开始创作', nav_signin: '登录',
    lang_label: '语言 / Language', lang_current: '中文',
    hero_title: '为音乐视频世界打造的合成器。',
    hero_subtitle: '多智能体 AI 编排 — 从歌词到成品 MV，仅需数分钟。',
    hero_cta: '立即开始创作',
    hero_trusted: '500+ 位创作者已加入内测',
    hero_quote: '"AIMV Studio 在 20 分钟内将我的创意变成了完整 MV。" — 内测用户',
    stats_clips: 'AI 片段已生成', stats_projects: '项目已创建', stats_models: 'AI 模型集成',
    music_videos_title: '音乐视频',
    ai_gen_title: 'AI 生成分镜',
    ai_gen_desc: '描述你的创意，编剧 Agent 自动生成逐镜分镜脚本。图像与视频片段由 Z-image、Wan2.2 等顶尖模型生成，无需拍摄。',
    multi_model_title: '多模型管线',
    multi_model_desc: '可在 Seedance 2.0、Veo 3.1、Grok Video 1.0 和 Wan2.2 14B 之间按镜头切换，或由导演 Agent 自动决策。',
    multi_model_note: 'AIMV Studio 像一个专业剪辑软件，但整条时间轴由 AI 撰写。',
    pipeline_title: 'Agent 协作流水线',
    pipeline_subtitle: '四个专职 AI Agent 串行协作，将创意描述转化为完整 MV',
    pipeline_note: '每个 Agent 通过结构化 JSON 通信。验证 Agent 闭合质量控制环路，自动重试低分片段。',
    music_demo_title: '音乐分析引擎',
    music_demo_subtitle: 'BPM 检测 · 结构分段 · 歌词转录 — 全部驱动视频生成',
    music_demo_bpm: 'BPM',
    models_title: 'AI 模型矩阵',
    models_subtitle: '按镜头手动选择，或由导演 Agent 自动路由',
    models_tab_image: '图像', models_tab_video: '视频', models_tab_music: '音乐',
    model_open: '开源', model_commercial: '商业',
    export_title: '多平台导出',
    export_subtitle: '一键导出，自动响度标准化（−14 LUFS / EBU R128）+ SRT 字幕烧录',
    testimonials_title: '创作者评价',
    testimonials_subtitle: '内测创作者已使用 AIMV Studio 生成超过 10,000 个 AI 视频片段。',
    t1_name: '林威',        t1_role: '独立音乐制作人',
    t1_quote: 'AIMV Studio 仅凭几句描述就理解了我的风格，分镜脚本完美还原了情绪，生成的镜头几乎不需要修改。',
    t2_name: '赵明',        t2_role: 'MV 导演',
    t2_quote: '多智能体管线让我印象深刻。我像对待真实团队一样给它简报，它真的交付了我想要的东西。',
    t3_name: 'Sara K.',     t3_role: '电子音乐艺术家',
    t3_quote: '我试过所有 AI 视频工具，AIMV Studio 是唯一一个真正以音乐为驱动的系统。',
    t4_name: '陈洁',        t4_role: '创作歌手',
    t4_quote: 'BPM 同步剪辑和自动响度标准化（−14 LUFS）为我节省了大量后期时间。',
    t5_name: 'Alex Turner', t5_role: '视觉艺术家 / 导演',
    t5_quote: '20+ 个镜头之间的角色一致性，我以为会让任何 AI 崩溃。AIMV Studio 全程表现完美。',
    t6_name: '王芳',        t6_role: '内容创作者',
    t6_quote: '从一句描述到导出成品 MV 只用了 18 分钟，质量让我真的很震惊。',
    what_you_create_title: '你可以创作的内容',
    what_you_create_subtitle: '拥有无限风格多样性的 AI 生成音乐视频。',
    news_title: '新闻与更新',
    news_1: 'AIMV Studio 1.0：完整多智能体 MV 生成管线正式上线',
    news_2: 'Wan2.2 14B 集成：Apache 2.0 授权的开源 4K 视频生成能力',
    news_3: '真实音频分段：MFCC + 聚类实现节拍精准剪辑',
    news_date_1: '2025/03/15', news_date_2: '2025/02/28', news_date_3: '2025/01/20',
    faq_title: '常见问题',
    faq_1_q: '什么是 AIMV Studio？',
    faq_1_a: 'AIMV Studio 是 AI 音乐视频平台。四个专业 Agent — 编剧、导演、音乐制作人、验证员 — 协作完成 MV 的规划、生成与审核。',
    faq_2_q: '我拥有生成视频的版权吗？',
    faq_2_a: '你对所有创建的视频拥有完整版权。我们不主张任何权益，也不会在未经许可的情况下使用你的内容。',
    faq_3_q: '支持哪些 AI 模型？',
    faq_3_a: 'Z-image 生图；Wan2.2 14B、Seedance 2.0、Veo 3.1、Grok Video 1.0 生视频；ACEStep 1.5、Suno、Google Lyria 生音乐。',
    faq_4_q: '音乐分析如何工作？',
    faq_4_a: 'librosa 进行 BPM 和节拍检测，MFCC + chroma 特征结合层次聚类实现结构分段，faster-whisper 转录歌词，全部驱动视频剪辑同步。',
    footer_tagline: '由热爱 AI 与音乐的学生构建，开源，社区驱动。',
    footer_product: '产品', footer_p1: '开始创作', footer_p2: '作品库', footer_p3: '我的项目', footer_p4: 'API 文档',
    footer_models: 'AI 模型', footer_m1: 'Z-image', footer_m2: 'Wan2.2 14B', footer_m3: 'Seedance 2.0', footer_m4: 'ACEStep 1.5',
    footer_more: '更多', footer_more1: 'GitHub', footer_more2: '文档', footer_more3: '关于', footer_more4: '开源',
    footer_socials: '社区', footer_s1: 'GitHub', footer_s2: 'Discord', footer_s3: 'Bilibili', footer_s4: 'Twitter / X',
  },
} as const

type LangKey = keyof typeof i18n.en
const t = computed(() => i18n[lang.value] as Record<LangKey, string>)

function toggleLang() {
  langStore.setLang(lang.value === 'en' ? 'zh' : 'en')
  document.documentElement.lang = lang.value === 'zh' ? 'zh-CN' : 'en'
}

// ─── routing ─────────────────────────────────────────────────────────────────
function startCreating() {
  router.push('/create')
}

// ─── carousel ────────────────────────────────────────────────────────────────
interface SlideItem { url: string; title: string; desc: string; pic: string }

const videoSources = [
  { bvid: 'BV1xjvvBwEZq', url: 'https://www.bilibili.com/video/BV1xjvvBwEZq/',
    fallback: { title: '大二期末作品MV《几分之几》', desc: '感谢真诚的影像，汇集每一个真诚创作的你。第一次和好朋友担任主创创作的作品。', pic: 'https://i1.hdslb.com/bfs/archive/b9316f0f07d2b17a5c9cf2231a570f27ade30e9e.jpg' } },
  { bvid: 'BV1gpyGBwEie', url: 'https://www.bilibili.com/video/BV1gpyGBwEie/',
    fallback: { title: '他不懂（RNB版）', desc: '当rnb碰到张杰的《他不懂》', pic: 'https://i0.hdslb.com/bfs/archive/395908458c09a21a72da46fec62f0abaab910e8b.jpg' } },
  { bvid: 'BV1psQ8YfEXU', url: 'https://www.bilibili.com/video/BV1psQ8YfEXU/',
    fallback: { title: '【4K60FPS】IU李知恩《Blueming》超甜美现场！', desc: '官方现场。IU真的很可爱，这首《Blueming》是IU很经典的一首歌曲。', pic: 'https://i1.hdslb.com/bfs/archive/cb3efec92dfe0c03f262e88bf2b7a7b4daa47b52.jpg' } },
]

const slides = ref<SlideItem[]>(videoSources.map(s => ({ url: s.url, ...s.fallback })))
const activeIndex = ref(0)
let carouselTimer: ReturnType<typeof setInterval> | null = null
let bpmTimer: ReturnType<typeof setInterval> | null = null

function goTo(i: number) { activeIndex.value = ((i % slides.value.length) + slides.value.length) % slides.value.length }
function prevSlide() { goTo(activeIndex.value - 1); restartCarousel() }
function nextSlide() { goTo(activeIndex.value + 1); restartCarousel() }
function dotClick(i: number) { goTo(i); restartCarousel() }
function startCarousel() { carouselTimer = setInterval(() => goTo(activeIndex.value + 1), 5000) }
function stopCarousel() { if (carouselTimer) { clearInterval(carouselTimer); carouselTimer = null } }
function restartCarousel() { stopCarousel(); startCarousel() }

async function fetchSlide(src: typeof videoSources[0]): Promise<SlideItem> {
  try {
    const r = await fetch(`https://api.bilibili.com/x/web-interface/view?bvid=${src.bvid}`)
    const j = await r.json()
    if (j.code !== 0) throw new Error()
    const d = j.data
    return { url: src.url, title: String(d.title || src.fallback.title).replace(/[<>]/g, '').trim(), desc: String(d.desc || src.fallback.desc).replace(/[<>]/g, '').trim(), pic: d.pic?.startsWith('http') ? d.pic : src.fallback.pic }
  } catch { return { url: src.url, ...src.fallback } }
}

// ─── agent pipeline ───────────────────────────────────────────────────────────
const agentActive = ref(0)
let agentTimer: ReturnType<typeof setInterval> | null = null

const agents = computed(() => lang.value === 'zh' ? [
  { name: '编剧 Agent', sub: 'Screenwriter', color: '#8d5cff', outputs: ['分镜脚本', 'CharacterBank', '情绪 / 节奏分析'] },
  { name: '导演 Agent', sub: 'Director', color: '#f3b2ff', outputs: ['镜头提示词', 'ShotRouter 路由', 'Frame Chaining'] },
  { name: '音乐制作人 Agent', sub: 'Music Producer', color: '#5cf3ff', outputs: ['音乐风格方案', '模型选择', '响度规范化'] },
  { name: '验证 Agent', sub: 'Verifier', color: '#ffcf5c', outputs: ['质量评分 1–5', '自动重试 ≤3次', 'A/B 版本对比'] },
] : [
  { name: 'Screenwriter', sub: 'Agent', color: '#8d5cff', outputs: ['Shot storyboard', 'CharacterBank', 'Mood/rhythm analysis'] },
  { name: 'Director', sub: 'Agent', color: '#f3b2ff', outputs: ['Shot prompts', 'ShotRouter routing', 'Frame Chaining'] },
  { name: 'Music Producer', sub: 'Agent', color: '#5cf3ff', outputs: ['Music style plan', 'Model selection', 'Loudness norm'] },
  { name: 'Verifier', sub: 'Agent', color: '#ffcf5c', outputs: ['Quality score 1–5', 'Auto-retry ≤3×', 'A/B comparison'] },
])

// ─── music analysis demo ──────────────────────────────────────────────────────
const bpmDisplay = ref(0)
const playheadPct = ref(0)

const waveformBars = Array.from({ length: 56 }, (_, i) => {
  const center = 28
  const dist = Math.abs(i - center) / center
  const base = Math.max(12, 88 - dist * 48)
  return { height: base * (0.55 + Math.random() * 0.45), delay: +(Math.random() * 1.8).toFixed(2) }
})

const segments = computed(() => lang.value === 'zh'
  ? [{ label: '前奏', w: 9, color: '#8d5cff' }, { label: '主歌', w: 21, color: '#5cf3ff' }, { label: '副歌', w: 27, color: '#f3b2ff' }, { label: '主歌', w: 18, color: '#5cf3ff' }, { label: '间奏', w: 10, color: '#ffcf5c' }, { label: '副歌', w: 15, color: '#f3b2ff' }]
  : [{ label: 'Intro', w: 9, color: '#8d5cff' }, { label: 'Verse', w: 21, color: '#5cf3ff' }, { label: 'Chorus', w: 27, color: '#f3b2ff' }, { label: 'Verse', w: 18, color: '#5cf3ff' }, { label: 'Bridge', w: 10, color: '#ffcf5c' }, { label: 'Chorus', w: 15, color: '#f3b2ff' }])

const demoLyrics = [
  '♪  Somewhere between the beat and the soul',
  '♪  AI analyzing 128 BPM — 4 segments detected',
  '♪  Chorus at 01:14 — high energy → 3 clips queued',
  '♪  faster-whisper transcription complete',
  '♪  Frame Chaining: shot 7 anchored to beat drop',
]
const lyricIndex = ref(0)

// ─── model matrix ─────────────────────────────────────────────────────────────
const modelTab = ref<'image' | 'video' | 'music'>('video')

const modelData = computed(() => {
  const zh = lang.value === 'zh'
  return {
    image: [
      {
        name: 'Z-image', license: 'open', color: '#4ade80',
        tag: zh ? '本地部署' : 'Self-hosted',
        specs: zh ? ['SD 架构', 'WebUI API', '零费用'] : ['SD arch', 'WebUI API', 'Free'],
        bestFor: zh ? '角色参考图 · 快速迭代' : 'Character refs · Fast iteration',
        desc: zh ? 'Stable Diffusion 架构，通过 WebUI API 本地运行，零 API 费用，完全可控。' : 'Stable Diffusion architecture, runs locally via WebUI API. Zero API cost, full control.',
      },
      {
        name: 'FLUX.1 Dev', license: 'open', color: '#818cf8',
        tag: zh ? '顶级质量' : 'Top Quality',
        specs: zh ? ['12B 参数', '1024px', 'Apache 2.0'] : ['12B params', '1024px', 'Apache 2.0'],
        bestFor: zh ? '高细节写实 · 复杂场景构图' : 'Photorealistic · Complex composition',
        desc: zh ? 'Black Forest Labs 出品，12B 参数扩散模型，图像细节与结构质量均居开源前列。' : 'By Black Forest Labs. 12B-param diffusion model — state-of-the-art detail and structure quality.',
      },
      {
        name: 'Stable Diffusion 3.5', license: 'open', color: '#fb923c',
        tag: zh ? '开源' : 'Open Source',
        specs: zh ? ['8B / 2.5B 版本', '多提示词文本框', '本地/云端'] : ['8B / 2.5B', 'Multi-prompt', 'Local / Cloud'],
        bestFor: zh ? '风格化插画 · 国风 · 幻想场景' : 'Stylized art · Fantasy · Ink painting',
        desc: zh ? 'Stability AI 最新 MMDiT 架构，文字渲染与多主体场景表现更强，风格化效果突出。' : "Stability AI's MMDiT architecture. Better text rendering and multi-subject scenes.",
      },
      {
        name: 'DALL-E 3', license: 'commercial', color: '#22d3ee',
        tag: zh ? '强提示词遵循' : 'Prompt-faithful',
        specs: zh ? ['OpenAI', '1024 / 1792px', 'API 调用'] : ['OpenAI', '1024 / 1792px', 'API call'],
        bestFor: zh ? '精准叙事镜头 · 品牌物料' : 'Precise narrative shots · Brand assets',
        desc: zh ? 'OpenAI 旗舰图像模型，提示词遵循度极高，适合需要精准表达创意意图的叙事镜头。' : "OpenAI's flagship image model with the highest prompt fidelity. Best for precise narrative shots.",
      },
      {
        name: 'Midjourney v6', license: 'commercial', color: '#f472b6',
        tag: zh ? '最佳美学' : 'Best Aesthetic',
        specs: zh ? ['v6.1 权重', '1:1 / 2:3 / 16:9', 'Discord / API'] : ['v6.1 weights', '1:1 / 2:3 / 16:9', 'Discord / API'],
        bestFor: zh ? 'K-Pop · 时尚大片 · 广告视觉' : 'K-Pop · Fashion editorial · Ad visuals',
        desc: zh ? '公认美学质量最强的商业图像模型，风格迁移与人物写真效果尤其出色。' : 'Industry-leading aesthetic quality. Exceptional for style transfer and portrait photography.',
      },
    ],
    video: [
      {
        name: 'Wan2.2 14B', license: 'open', color: '#4ade80',
        tag: zh ? '开源 4K' : 'Open 4K',
        specs: zh ? ['14B 参数', '4K 分辨率', 'Apache 2.0'] : ['14B params', '4K res', 'Apache 2.0'],
        bestFor: zh ? '国风 · 独立电影 · 长场景' : 'Indie · Classical · Long clips',
        desc: zh ? '14B 参数开源视频模型，Apache 2.0 授权，支持 4K 分辨率，适合本地部署的团队。' : '14B param open-source model, Apache 2.0, 4K resolution — ideal for self-hosted pipelines.',
      },
      {
        name: 'Seedance 2.0', license: 'commercial', color: '#60a5fa',
        tag: zh ? '极速' : 'Fast',
        specs: zh ? ['字节跳动', '< 30s 生成', '1080p'] : ['ByteDance', '< 30s gen', '1080p'],
        bestFor: zh ? 'K-Pop · 电子舞曲 · 高动态镜头' : 'K-Pop · EDM · High motion clips',
        desc: zh ? '字节跳动极速视频模型，高动态与舞蹈类 MV 首选，生成速度业界领先。' : "ByteDance's fastest video model — top choice for high-motion and dance music videos.",
      },
      {
        name: 'Veo 3.1', license: 'commercial', color: '#f59e0b',
        tag: zh ? '高质量' : 'HQ',
        specs: zh ? ['Google DeepMind', '1080p 60fps', '时序一致性'] : ['Google DeepMind', '1080p 60fps', 'Temporal cons.'],
        bestFor: zh ? '人物近景 · 情感叙事 · 流畅动作' : 'Close-ups · Emotion · Fluid motion',
        desc: zh ? 'Google DeepMind 视频模型，时序一致性出色，人物运动流畅，情感叙事类 MV 首选。' : "Google DeepMind's model — excellent temporal consistency and smooth motion for narrative MVs.",
      },
      {
        name: 'Grok Video 1.0', license: 'commercial', color: '#e879f9',
        tag: zh ? '创意' : 'Creative',
        specs: zh ? ['xAI', '风格化优先', 'API 调用'] : ['xAI', 'Style-first', 'API call'],
        bestFor: zh ? '赛博朋克 · 抽象艺术 · 奇幻风格' : 'Cyberpunk · Abstract · Fantasy',
        desc: zh ? 'xAI 视频模型，创意解读能力强，赛博朋克与强风格化效果表现尤为突出。' : "xAI's video model with strong creative interpretation — best for cyberpunk and stylized scenes.",
      },
      {
        name: 'Kling 2.0', license: 'commercial', color: '#f87171',
        tag: zh ? '高动态' : 'High Motion',
        specs: zh ? ['快手', '5s / 10s', '1080p'] : ['Kuaishou', '5s / 10s', '1080p'],
        bestFor: zh ? '舞蹈编排 · 动感镜头 · 运动追踪' : 'Choreography · Action · Motion tracking',
        desc: zh ? '快手 Kling 2.0，舞蹈与人体动作生成质量优异，是编舞类 MV 的专属利器。' : "Kuaishou's Kling 2.0 excels at human body motion — the go-to model for dance choreography MVs.",
      },
      {
        name: 'CogVideoX 5B', license: 'open', color: '#34d399',
        tag: zh ? '开源' : 'Open Source',
        specs: zh ? ['智谱 AI', '5B 参数', '720p · Apache 2.0'] : ['Zhipu AI', '5B params', '720p · Apache 2.0'],
        bestFor: zh ? '国风 · 复古迪斯科 · 写实场景' : 'Classical · Retro · Realistic scenes',
        desc: zh ? '智谱 AI 开源视频模型，720p 输出，对国风与写实场景理解精准，零成本本地部署。' : 'Zhipu AI open-source model. 720p output — great understanding of realistic and classical scenes.',
      },
    ],
    music: [
      {
        name: 'ACEStep 1.5', license: 'open', color: '#4ade80',
        tag: zh ? '本地部署' : 'Self-hosted',
        specs: zh ? ['本地运行', '全风格', '时长可控'] : ['Local run', 'All genres', 'Ctrl duration'],
        bestFor: zh ? '仅配乐 · 器乐背景音 · 隐私优先' : 'Instrumental BGM · Privacy-first',
        desc: zh ? '高质量音乐生成，本地运行，完全控制风格与时长，无任何 API 费用。' : 'High-quality music generation, runs locally. Full style and duration control, zero API cost.',
      },
      {
        name: 'Suno v4', license: 'commercial', color: '#fb923c',
        tag: zh ? '顶级人声' : 'HQ Vocals',
        specs: zh ? ['有/无人声', '流行/EDM/嘻哈', '< 10s 生成'] : ['Vocal / Inst.', 'Pop/EDM/Hip-hop', '< 10s gen'],
        bestFor: zh ? '流行 · K-Pop · R&B · 嘻哈' : 'Pop · K-Pop · R&B · Hip-hop',
        desc: zh ? 'Suno v4 人声质量与制作细节行业顶尖，流行与电子类 MV 背景乐首选。' : 'Industry-best vocal quality and production detail. Top choice for pop and EDM MVs.',
      },
      {
        name: 'Google Lyria', license: 'commercial', color: '#60a5fa',
        tag: zh ? '交响乐' : 'Orchestral',
        specs: zh ? ['Google DeepMind', '交响 · 管弦', '多乐器层次'] : ['Google DeepMind', 'Symphonic', 'Multi-instrument'],
        bestFor: zh ? '史诗 MV · 古典 · 影视配乐' : 'Epic · Classical · Cinematic score',
        desc: zh ? 'Google DeepMind 出品，擅长交响乐与复杂编曲，史诗感 MV 的理想选择。' : 'Specialized in orchestral and complex arrangements. Ideal for epic cinematic MVs.',
      },
      {
        name: 'Udio', license: 'commercial', color: '#c084fc',
        tag: zh ? '音乐性强' : 'Musical Depth',
        specs: zh ? ['人声/无人声', '高动态范围', '实验性流派'] : ['Vocal / Inst.', 'High dynamic range', 'Experimental'],
        bestFor: zh ? '实验电子 · 爵士 · 融合流派' : 'Experimental · Jazz · Fusion genres',
        desc: zh ? '音乐性与音色质量出色，对爵士、融合与实验电子等复杂流派的理解尤为深刻。' : 'Exceptional musicality and timbre. Best for jazz fusion and experimental electronic genres.',
      },
      {
        name: 'MusicGen Large', license: 'open', color: '#34d399',
        tag: zh ? '开源' : 'Open Source',
        specs: zh ? ['Meta AI', '3.3B 参数', '单/立体声'] : ['Meta AI', '3.3B params', 'Mono / Stereo'],
        bestFor: zh ? '器乐背景 · 氛围音效 · 学术研究' : 'Instrumental · Ambient · Research',
        desc: zh ? 'Meta AI 开源音乐模型，无人声器乐生成能力强，适合纯配乐类 MV 与低成本制作。' : "Meta AI's open-source model — excellent for instrumental generation, great for budget productions.",
      },
      {
        name: 'YuE', license: 'open', color: '#f472b6',
        tag: zh ? '中文首选' : 'CN Optimized',
        specs: zh ? ['开源', '中英双语', '歌词驱动'] : ['Open source', 'ZH / EN bilingual', 'Lyrics-aware'],
        bestFor: zh ? '国风 · 中文流行 · 古典融合' : 'C-Pop · Chinese Classical · Fusion',
        desc: zh ? '专为中文音乐优化的开源大模型，支持歌词驱动生成，国风与中文流行 MV 首选。' : 'Open-source model optimized for Chinese music. Lyrics-driven generation for C-Pop and Classical MVs.',
      },
    ],
  }
})

// ─── export presets ───────────────────────────────────────────────────────────
const exportPresets = computed(() => {
  const zh = lang.value === 'zh'
  return [
    {
      id: 'douyin', name: zh ? '抖音' : 'Douyin', ratio: '9:16', w: 1080, h: 1920, bitrate: '4M', rw: 9, rh: 16,
      color: '#FE2C55',
      // TikTok / Douyin logo (SimpleIcons)
      svgPath: 'M12.525.02c1.31-.02 2.61-.01 3.91-.02.08 1.53.63 3.09 1.75 4.17 1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.05-2.89-.35-4.2-.97-.57-.26-1.1-.59-1.62-.93-.01 2.92.01 5.84-.02 8.75-.08 1.4-.54 2.79-1.35 3.94-1.31 1.92-3.58 3.17-5.91 3.21-1.43.08-2.86-.31-4.08-1.03-2.02-1.19-3.44-3.37-3.65-5.71-.02-.5-.03-1-.01-1.49.18-1.9 1.12-3.72 2.58-4.96 1.66-1.44 3.98-2.13 6.15-1.72.02 1.48-.04 2.96-.04 4.44-.99-.32-2.15-.23-3.02.37-.63.41-1.11 1.04-1.36 1.75-.21.51-.15 1.07-.14 1.61.24 1.64 1.82 3.02 3.5 2.87 1.12-.01 2.19-.66 2.77-1.61.19-.33.4-.67.41-1.06.1-1.79.06-3.57.07-5.36.01-4.03-.01-8.05.02-12.07z',
    },
    {
      id: 'bilibili', name: 'Bilibili', ratio: '16:9', w: 1920, h: 1080, bitrate: '6M', rw: 16, rh: 9,
      color: '#00A1D6',
      // Bilibili logo (SimpleIcons)
      svgPath: 'M17.813 4.653h.854c1.51.054 2.769.578 3.773 1.574 1.004.995 1.524 2.249 1.56 3.76v7.36c-.036 1.51-.556 2.769-1.56 3.773s-2.262 1.524-3.773 1.56H5.333c-1.51-.036-2.769-.556-3.773-1.56S.036 18.858 0 17.347v-7.36c.036-1.511.556-2.765 1.56-3.76 1.004-.996 2.262-1.52 3.773-1.574h.774l-1.174-1.12a1.234 1.234 0 0 1-.373-.906c0-.356.124-.658.373-.907l.027-.027c.267-.249.573-.373.92-.373.347 0 .653.124.92.373L9.653 4.44c.071.071.134.142.187.213h4.267a.836.836 0 0 1 .16-.213l2.853-2.747c.267-.249.573-.373.92-.373.347 0 .662.151.929.4.267.249.391.551.391.907 0 .355-.124.657-.373.906zM5.333 7.24c-.746.018-1.373.276-1.88.773-.506.498-.769 1.13-.786 1.894v7.52c.017.764.28 1.395.786 1.893.507.498 1.134.756 1.88.773h13.334c.746-.017 1.373-.275 1.88-.773.506-.498.769-1.129.786-1.893v-7.52c-.017-.765-.28-1.396-.786-1.894-.507-.497-1.134-.755-1.88-.773zM8 11.107c.373 0 .684.124.933.373.25.249.383.569.4.96v1.173c-.017.391-.15.711-.4.96-.249.25-.56.374-.933.374s-.684-.125-.933-.374c-.25-.249-.383-.569-.4-.96V12.44c0-.373.129-.689.386-.947.258-.257.574-.386.947-.386zm8 0c.373 0 .684.124.933.373.25.249.383.569.4.96v1.173c-.017.391-.15.711-.4.96-.249.25-.56.374-.933.374s-.684-.125-.933-.374c-.25-.249-.383-.569-.4-.96V12.44c.017-.391.15-.711.4-.96.249-.249.56-.373.933-.373z',
    },
    {
      id: 'youtube', name: 'YouTube HQ', ratio: '16:9', w: 1920, h: 1080, bitrate: '8M', rw: 16, rh: 9,
      color: '#FF0000',
      // YouTube logo (SimpleIcons)
      svgPath: 'M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z',
    },
    {
      id: 'xiaohongshu', name: zh ? '小红书' : 'Xiaohongshu', ratio: '3:4', w: 1080, h: 1440, bitrate: '4M', rw: 3, rh: 4,
      color: '#FF2442',
      // Xiaohongshu — heart in rounded square
      svgPath: 'M20.5 3h-17A1.5 1.5 0 0 0 2 4.5v15A1.5 1.5 0 0 0 3.5 21h17a1.5 1.5 0 0 0 1.5-1.5v-15A1.5 1.5 0 0 0 20.5 3zm-8.5 13.9-5.99-5.6A3.15 3.15 0 0 1 5.5 8.5a3.5 3.5 0 0 1 6.5-1.8 3.5 3.5 0 0 1 6.5 1.8 3.15 3.15 0 0 1-.51 2.8L12 16.9z',
    },
    {
      id: 'instagram', name: 'Instagram', ratio: '9:16', w: 1080, h: 1920, bitrate: '3.5M', rw: 9, rh: 16,
      color: '#E4405F',
      // Instagram logo (SimpleIcons)
      svgPath: 'M12 0C8.74 0 8.333.015 7.053.072 5.775.132 4.905.333 4.14.63c-.789.306-1.459.717-2.126 1.384S.935 3.35.63 4.14C.333 4.905.131 5.775.072 7.053.012 8.333 0 8.74 0 12c0 3.259.014 3.668.072 4.948.058 1.277.26 2.148.558 2.913.306.788.717 1.459 1.384 2.126.667.666 1.336 1.079 2.126 1.384.766.296 1.636.499 2.913.558C8.333 23.988 8.74 24 12 24c3.259 0 3.668-.014 4.948-.072 1.277-.058 2.148-.261 2.913-.558.788-.306 1.459-.718 2.126-1.384.666-.667 1.079-1.335 1.384-2.126.296-.765.499-1.636.558-2.913.06-1.28.072-1.689.072-4.948 0-3.259-.014-3.667-.072-4.947-.059-1.277-.262-2.149-.558-2.913-.306-.789-.718-1.459-1.384-2.126C21.319 1.347 20.651.935 19.86.63c-.765-.297-1.636-.499-2.913-.558C15.667.012 15.26 0 12 0zm0 2.16c3.203 0 3.585.016 4.85.071 1.17.055 1.805.249 2.227.415.562.217.96.477 1.382.896.419.42.679.819.896 1.381.164.422.36 1.057.413 2.227.057 1.266.07 1.646.07 4.85s-.015 3.585-.074 4.85c-.061 1.17-.256 1.805-.421 2.227-.224.562-.479.96-.899 1.382-.419.419-.824.679-1.38.896-.42.164-1.065.36-2.235.413-1.274.057-1.649.07-4.859.07-3.211 0-3.586-.015-4.859-.074-1.171-.061-1.816-.256-2.236-.421-.569-.224-.96-.479-1.379-.899-.421-.419-.69-.824-.9-1.38-.165-.42-.359-1.065-.42-2.235-.045-1.26-.061-1.649-.061-4.844 0-3.196.016-3.586.061-4.861.061-1.17.255-1.814.42-2.234.21-.57.479-.96.9-1.381.419-.419.81-.689 1.379-.898.42-.166 1.051-.361 2.221-.421 1.275-.045 1.65-.06 4.859-.06l.045.03zm0 3.678c-3.405 0-6.162 2.76-6.162 6.162 0 3.405 2.76 6.162 6.162 6.162 3.405 0 6.162-2.76 6.162-6.162 0-3.405-2.76-6.162-6.162-6.162zM12 16c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z',
    },
    {
      id: 'original', name: zh ? '原始输出' : 'Original', ratio: '—', w: 0, h: 0, bitrate: '—', rw: 16, rh: 9,
      color: '#8d5cff',
      // Film frame icon
      svgPath: 'M18 4l2 4h-3l-2-4h-2l2 4h-3l-2-4H8l2 4H7L5 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V4h-4z',
    },
  ]
})

// ─── live stats (count-up) ────────────────────────────────────────────────────
const stats = ref({ clips: 0, projects: 0, models: 0 })
const statsTarget = { clips: 12847, projects: 634, models: 12 }

function animateStats() {
  const duration = 1800
  const start = Date.now()
  const tick = () => {
    const p = Math.min(1, (Date.now() - start) / duration)
    const ease = 1 - Math.pow(1 - p, 3)
    stats.value.clips    = Math.floor(statsTarget.clips    * ease)
    stats.value.projects = Math.floor(statsTarget.projects * ease)
    stats.value.models   = Math.floor(statsTarget.models   * ease)
    if (p < 1) requestAnimationFrame(tick)
  }
  requestAnimationFrame(tick)
}

// ─── misc static ─────────────────────────────────────────────────────────────
const galleryItems = [
  { title: 'K-Pop Visual Edit',    artist: 'Cyberpunk style',      bg: 'linear-gradient(135deg,#ff6b9d,#c051e0)', icon: '🎤', tag: 'K-Pop' },
  { title: 'Chinese Classical',    artist: 'Traditional ink',      bg: 'linear-gradient(135deg,#2d5016,#8b6914)', icon: '🎼', tag: '国风' },
  { title: 'Indie Film Aesthetic', artist: 'Golden hour',          bg: 'linear-gradient(135deg,#3a3a3a,#8b7355)', icon: '🎬', tag: 'Indie' },
  { title: 'Electronic Dance',     artist: 'Neon club scene',      bg: 'linear-gradient(135deg,#00e5ff,#aa00ff)', icon: '⚡', tag: 'EDM' },
  { title: 'Urban R&B',            artist: 'Street photography',   bg: 'linear-gradient(135deg,#667eea,#764ba2)', icon: '🎵', tag: 'R&B' },
  { title: 'Fantasy Epic',         artist: 'Cinematic orchestral', bg: 'linear-gradient(135deg,#a18cd1,#fbc2eb)', icon: '✨', tag: 'Epic' },
]

const avatarColors = ['#8d5cff', '#f3b2ff', '#5cf3ff', '#ff9bd1', '#ffcf5c']

const testimonials = computed(() => [
  { name: t.value.t1_name, role: t.value.t1_role, quote: t.value.t1_quote },
  { name: t.value.t2_name, role: t.value.t2_role, quote: t.value.t2_quote },
  { name: t.value.t3_name, role: t.value.t3_role, quote: t.value.t3_quote },
  { name: t.value.t4_name, role: t.value.t4_role, quote: t.value.t4_quote },
  { name: t.value.t5_name, role: t.value.t5_role, quote: t.value.t5_quote },
  { name: t.value.t6_name, role: t.value.t6_role, quote: t.value.t6_quote },
])

// ─── lifecycle ────────────────────────────────────────────────────────────────
let lyricTimer: ReturnType<typeof setInterval> | null = null
let playheadRAF: number | null = null
let playheadStart: number | null = null

function startPlayhead() {
  playheadStart = Date.now()
  const tick = () => {
    const elapsed = (Date.now() - playheadStart!) % 8000
    playheadPct.value = (elapsed / 8000) * 100
    playheadRAF = requestAnimationFrame(tick)
  }
  playheadRAF = requestAnimationFrame(tick)
}

onMounted(() => {
  // Only auto-detect browser language when the user has not saved a preference yet.
  // The lang store already restores 'aimv_lang' on init, so avoid overriding it here.
  if (!localStorage.getItem('aimv_lang')) {
    if ((navigator.language || '').toLowerCase().startsWith('zh')) {
      langStore.setLang('zh')
    }
  }

  Promise.all(videoSources.map(fetchSlide)).then(items => { slides.value = items })
  startCarousel()

  agentTimer = setInterval(() => { agentActive.value = (agentActive.value + 1) % 4 }, 2200)

  // BPM count-up
  let bpmCurrent = 0
  const BPM_TARGET = 128
  bpmTimer = setInterval(() => {
    bpmCurrent = Math.min(BPM_TARGET, bpmCurrent + 4)
    bpmDisplay.value = bpmCurrent
    if (bpmCurrent >= BPM_TARGET) { clearInterval(bpmTimer!); bpmTimer = null }
  }, 20)

  lyricTimer = setInterval(() => { lyricIndex.value = (lyricIndex.value + 1) % demoLyrics.length }, 3000)
  startPlayhead()
  setTimeout(animateStats, 300)
})

onUnmounted(() => {
  stopCarousel()
  if (agentTimer) clearInterval(agentTimer)
  if (lyricTimer) clearInterval(lyricTimer)
  if (bpmTimer) clearInterval(bpmTimer)
  if (playheadRAF) cancelAnimationFrame(playheadRAF)
})
</script>

<template>
  <div class="home-page">

    <!-- HEADER -->
    <header class="site-header">
      <div class="header-inner">
        <router-link to="/" class="logo">
          <span class="logo-text">AIMV Studio</span>
        </router-link>
        <nav class="nav-links">
          <router-link to="/gallery">{{ t.nav_gallery }}</router-link>
          <a href="#" @click.prevent="startCreating">{{ t.nav_create }}</a>
          <router-link to="/login">{{ t.nav_signin }}</router-link>
        </nav>
        <button class="lang-toggle" type="button" @click="toggleLang" :aria-label="t.lang_label">
          <span class="lang-label-text">{{ t.lang_label }}</span>
          <span class="lang-value">{{ t.lang_current }}</span>
        </button>
      </div>
    </header>

    <main>

      <!-- HERO -->
      <section class="hero">
        <div class="hero-shell">
          <div class="hero-media-layer" aria-hidden="true">
            <img src="/screenshots/home_hero.png" class="hero-bg-img" alt="" />
            <video src="/hero.mp4" autoplay muted loop playsinline poster="/screenshots/home_hero.png"></video>
          </div>
          <div class="hero-overlay">
            <div class="hero-content">
              <h1>{{ t.hero_title }}</h1>
              <h2>{{ t.hero_subtitle }}</h2>
              <a class="hero-cta" href="#" @click.prevent="startCreating">{{ t.hero_cta }}</a>
              <div class="hero-trusted">
                <p>{{ t.hero_trusted }}</p>
                <div class="hero-avatars">
                  <div v-for="(c, i) in avatarColors" :key="i" class="avatar-circle" :style="{ background: c }"></div>
                </div>
                <div class="hero-quote">{{ t.hero_quote }}</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- LIVE STATS BAR -->
      <div class="stats-bar">
        <div class="container stats-inner">
          <div class="stat-item">
            <span class="stat-num">{{ stats.clips.toLocaleString() }}+</span>
            <span class="stat-lbl">{{ t.stats_clips }}</span>
          </div>
          <div class="stat-div"></div>
          <div class="stat-item">
            <span class="stat-num">{{ stats.projects.toLocaleString() }}+</span>
            <span class="stat-lbl">{{ t.stats_projects }}</span>
          </div>
          <div class="stat-div"></div>
          <div class="stat-item">
            <span class="stat-num">{{ stats.models }}</span>
            <span class="stat-lbl">{{ t.stats_models }}</span>
          </div>
        </div>
      </div>

      <!-- MUSIC VIDEOS -->
      <section id="music-videos" class="section-dark">
        <div class="container">
          <div class="section-header"><h2>{{ t.music_videos_title }}</h2></div>
          <div class="mv-carousel" @mouseenter="stopCarousel" @mouseleave="startCarousel">
            <button class="carousel-btn" type="button" @click="prevSlide">&#8249;</button>
            <div class="carousel-track">
              <div class="carousel-slides" :style="{ transform: `translateX(-${activeIndex * 100}%)` }">
                <a v-for="(slide, idx) in slides" :key="idx" class="carousel-slide"
                   :href="slide.url" target="_blank" rel="noopener noreferrer">
                  <div class="slide-media"><img :src="slide.pic" :alt="slide.title" loading="lazy" /></div>
                  <div class="slide-info"><h3>{{ slide.title }}</h3><p>{{ slide.desc }}</p></div>
                </a>
              </div>
            </div>
            <button class="carousel-btn" type="button" @click="nextSlide">&#8250;</button>
            <div class="carousel-dots">
              <button v-for="(_, idx) in slides" :key="idx" type="button" class="carousel-dot"
                      :class="{ active: idx === activeIndex }" @click="dotClick(idx)"></button>
            </div>
          </div>
          <div class="feature-grid">
            <article class="feature-card">
              <img src="/screenshots/pipeline.png" class="feature-screenshot" alt="Storyboard pipeline" loading="lazy" />
              <h3>{{ t.ai_gen_title }}</h3><p>{{ t.ai_gen_desc }}</p>
            </article>
            <article class="feature-card">
              <img src="/screenshots/models.png" class="feature-screenshot" alt="Model selection" loading="lazy" />
              <h3>{{ t.multi_model_title }}</h3><p>{{ t.multi_model_desc }}</p>
              <p class="feature-note">{{ t.multi_model_note }}</p>
            </article>
          </div>
        </div>
      </section>

      <!-- ① AGENT PIPELINE -->
      <section id="pipeline" class="section-light">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.pipeline_title }}</h2>
            <p>{{ t.pipeline_subtitle }}</p>
          </div>
          <div class="pipeline-flow">
            <template v-for="(agent, idx) in agents" :key="agent.name">
              <div class="pipeline-agent" :class="{ active: agentActive === idx }"
                   :style="{ '--agent-color': agent.color }">
                <div class="agent-index">0{{ idx + 1 }}</div>
                <div class="agent-name">{{ agent.name }}</div>
                <div class="agent-sub">{{ agent.sub }}</div>
                <ul class="agent-outputs">
                  <li v-for="o in agent.outputs" :key="o">{{ o }}</li>
                </ul>
              </div>
              <div v-if="idx < agents.length - 1" class="pipeline-arrow"
                   :class="{ flowing: agentActive === idx }">
                <span class="arrow-dot"></span>
                <svg viewBox="0 0 40 12" fill="none">
                  <line x1="0" y1="6" x2="32" y2="6" stroke="currentColor" stroke-width="1.5" stroke-dasharray="4 3"/>
                  <polyline points="28,2 36,6 28,10" stroke="currentColor" stroke-width="1.5" fill="none"/>
                </svg>
              </div>
            </template>
          </div>
          <p class="pipeline-note">{{ t.pipeline_note }}</p>
        </div>
      </section>

      <!-- APP PREVIEW -->
      <section class="section-dark app-preview-section">
        <div class="container">
          <div class="section-header">
            <h2>{{ lang === 'zh' ? '创作室一览' : 'Studio at a glance' }}</h2>
            <p>{{ lang === 'zh' ? '从 AI 对话规划到多轨分镜预览，一体化创作体验' : 'From AI chat planning to multi-track storyboard preview — one unified studio' }}</p>
          </div>
          <div class="app-preview-grid">
            <a class="app-preview-card" href="#" @click.prevent="startCreating">
              <img src="/screenshots/create.png" alt="Create studio" loading="lazy" />
              <div class="app-preview-label">{{ lang === 'zh' ? '🎬 AI 创作室' : '🎬 AI Studio' }}</div>
            </a>
            <a class="app-preview-card" href="#" @click.prevent="startCreating">
              <img src="/screenshots/projects.png" alt="My projects" loading="lazy" />
              <div class="app-preview-label">{{ lang === 'zh' ? '📂 我的项目' : '📂 My Projects' }}</div>
            </a>
            <a class="app-preview-card" href="#" @click.prevent="startCreating">
              <img src="/screenshots/export.png" alt="Export editor" loading="lazy" />
              <div class="app-preview-label">{{ lang === 'zh' ? '📤 导出编辑器' : '📤 Export Editor' }}</div>
            </a>
          </div>
        </div>
      </section>

      <!-- ② MUSIC ANALYSIS DEMO -->
      <section id="music-demo" class="section-dark">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.music_demo_title }}</h2>
            <p>{{ t.music_demo_subtitle }}</p>
          </div>
          <div class="music-demo">
            <!-- BPM badge -->
            <div class="bpm-badge">
              <span class="bpm-num">{{ bpmDisplay }}</span>
              <span class="bpm-label">{{ t.music_demo_bpm }}</span>
            </div>
            <!-- Waveform -->
            <div class="waveform-wrap">
              <div class="waveform">
                <div v-for="(bar, i) in waveformBars" :key="i" class="waveform-bar"
                     :style="{ height: bar.height + '%', animationDelay: bar.delay + 's' }"></div>
              </div>
              <!-- playhead -->
              <div class="playhead" :style="{ left: playheadPct + '%' }"></div>
            </div>
            <!-- Segment timeline -->
            <div class="segment-bar">
              <div v-for="seg in segments" :key="seg.label" class="segment"
                   :style="{ width: seg.w + '%', background: seg.color + '33', borderColor: seg.color }">
                <span>{{ seg.label }}</span>
              </div>
            </div>
            <!-- Lyrics ticker -->
            <div class="lyrics-ticker">
              <Transition name="lyric" mode="out-in">
                <span :key="lyricIndex">{{ demoLyrics[lyricIndex] }}</span>
              </Transition>
            </div>
          </div>
        </div>
      </section>

      <!-- ③ MODEL MATRIX -->
      <section id="models" class="section-light">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.models_title }}</h2>
            <p>{{ t.models_subtitle }}</p>
          </div>
          <div class="model-tabs">
            <button v-for="tab in (['image','video','music'] as const)" :key="tab"
                    class="model-tab" :class="{ active: modelTab === tab }"
                    @click="modelTab = tab">
              {{ t[`models_tab_${tab}` as LangKey] }}
            </button>
          </div>
          <div class="model-grid">
            <article v-for="m in modelData[modelTab]" :key="m.name" class="model-card"
                     :style="{ '--mc': m.color }">
              <div class="model-card-top">
                <span class="model-name">{{ m.name }}</span>
                <span class="model-badge" :class="m.license">
                  {{ m.license === 'open' ? t.model_open : t.model_commercial }}
                </span>
              </div>
              <span class="model-tag">{{ m.tag }}</span>
              <div class="model-specs">
                <span v-for="s in m.specs" :key="s" class="model-spec-chip">{{ s }}</span>
              </div>
              <p class="model-bestfor">
                <strong>{{ lang === 'zh' ? '适用：' : 'Best for: ' }}</strong>{{ m.bestFor }}
              </p>
              <p class="model-desc">{{ m.desc }}</p>
            </article>
          </div>
        </div>
      </section>

      <!-- ④ EXPORT PRESETS -->
      <section id="export" class="section-dark">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.export_title }}</h2>
            <p>{{ t.export_subtitle }}</p>
          </div>
          <div class="export-grid">
            <div v-for="p in exportPresets" :key="p.id" class="export-card" :style="{ '--ep': p.color }">
              <div class="export-logo-wrap">
                <svg class="export-logo-svg" viewBox="0 0 24 24" fill="currentColor" :style="{ color: p.color }">
                  <path :d="p.svgPath" />
                </svg>
              </div>
              <div class="export-info">
                <div class="export-name">{{ p.name }}</div>
                <div class="export-ratio">{{ p.ratio }}</div>
                <div class="export-specs" v-if="p.w">{{ p.w }}×{{ p.h }} · {{ p.bitrate }}</div>
                <div class="export-specs" v-else>{{ lang === 'zh' ? '无损输出' : 'Lossless' }}</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- TESTIMONIALS -->
      <section class="testimonials section-light">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.testimonials_title }}</h2>
            <p>{{ t.testimonials_subtitle }}</p>
          </div>
          <div class="testimonial-grid">
            <article class="testimonial-card" v-for="(item, idx) in testimonials" :key="item.name">
              <div class="testimonial-header">
                <div class="t-avatar" :style="{ background: avatarColors[idx % avatarColors.length] }">
                  {{ item.name[0] }}
                </div>
                <div><h4>{{ item.name }}</h4><span>{{ item.role }}</span></div>
              </div>
              <p>{{ item.quote }}</p>
            </article>
          </div>
        </div>
      </section>

      <!-- GALLERY -->
      <section id="what-you-create" class="section-dark">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.what_you_create_title }}</h2>
            <p>{{ t.what_you_create_subtitle }}</p>
          </div>
          <div class="gallery-grid">
            <div class="gallery-tile" v-for="item in galleryItems" :key="item.title">
              <div class="gallery-tile-img" :style="{ background: item.bg }">
                <span class="gallery-tile-icon">{{ item.icon }}</span>
                <span class="gallery-tile-tag">{{ item.tag }}</span>
              </div>
              <div class="gallery-tile-meta">
                <span>{{ item.title }}</span>
                <small>{{ item.artist }}</small>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- NEWS -->
      <section id="blog" class="section-light">
        <div class="container">
          <div class="section-header"><h2>{{ t.news_title }}</h2></div>
          <div class="news-grid">
            <article class="news-card" v-for="n in 3" :key="n">
              <a href="#">{{ t[`news_${n}` as LangKey] }}</a>
              <span>{{ t[`news_date_${n}` as LangKey] }}</span>
            </article>
          </div>
        </div>
      </section>

      <!-- FAQ -->
      <section id="faq" class="section-dark">
        <div class="container">
          <div class="section-header"><h2>{{ t.faq_title }}</h2></div>
          <div class="faq-grid">
            <article class="faq-card" v-for="n in 4" :key="n">
              <h3>{{ t[`faq_${n}_q` as LangKey] }}</h3>
              <p>{{ t[`faq_${n}_a` as LangKey] }}</p>
            </article>
          </div>
        </div>
      </section>

    </main>

    <!-- FOOTER -->
    <footer class="site-footer">
      <div class="container footer-grid">
        <div>
          <div class="footer-logo">AIMV Studio</div>
          <p>{{ t.footer_tagline }}</p>
        </div>
        <div>
          <h4>{{ t.footer_product }}</h4>
          <ul>
            <li><a href="#" @click.prevent="startCreating">{{ t.footer_p1 }}</a></li>
            <li><router-link to="/gallery">{{ t.footer_p2 }}</router-link></li>
            <li><router-link to="/projects">{{ t.footer_p3 }}</router-link></li>
            <li><a href="#">{{ t.footer_p4 }}</a></li>
          </ul>
        </div>
        <div>
          <h4>{{ t.footer_models }}</h4>
          <ul><li>{{ t.footer_m1 }}</li><li>{{ t.footer_m2 }}</li><li>{{ t.footer_m3 }}</li><li>{{ t.footer_m4 }}</li></ul>
        </div>
        <div>
          <h4>{{ t.footer_socials }}</h4>
          <ul>
            <li><a href="#">{{ t.footer_s1 }}</a></li><li><a href="#">{{ t.footer_s2 }}</a></li>
            <li><a href="#">{{ t.footer_s3 }}</a></li><li><a href="#">{{ t.footer_s4 }}</a></li>
          </ul>
        </div>
      </div>
    </footer>

  </div>
</template>

<style scoped>
.home-page { min-height: 100vh; font-family: "Geist","Inter",system-ui,-apple-system,sans-serif; }
.home-page a { color: inherit; text-decoration: none; }

/* ── Header ────────────────────────────────────────────────────────────────── */
.site-header { position:fixed;top:0;left:0;width:100%;background-color:#121212;
  box-shadow:0 2px 4px -1px rgba(0,0,0,.2),0 4px 5px 0 rgba(0,0,0,.14),0 1px 10px 0 rgba(0,0,0,.12);
  background-image:linear-gradient(rgba(255,255,255,.09),rgba(255,255,255,.09));z-index:100; }
.header-inner { display:flex;align-items:center;padding:0 24px;min-height:64px;
  margin:0 auto;width:min(1180px,92vw);gap:24px; }
.logo { display:flex;align-items:center;gap:8px;color:var(--text) !important; }
.logo-text { font-size:18px;font-weight:700;background:var(--accent-gradient);
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text; }
.nav-links { display:flex;gap:20px;font-size:.9rem; }
.nav-links a { color:var(--text-muted);transition:color .2s; }
.nav-links a:hover { color:var(--text); }
.lang-toggle { margin-left:auto;padding:8px 14px;border-radius:12px;border:1px solid rgba(255,255,255,.4);
  background:linear-gradient(135deg,rgba(255,255,255,.15),rgba(141,92,255,.2));color:white;
  font-size:.875rem;cursor:pointer;display:inline-flex;align-items:center;gap:8px;
  box-shadow:0 4px 10px rgba(0,0,0,.25);white-space:nowrap;flex-shrink:0; }
.lang-label-text { font-weight:600;letter-spacing:.3px; }
.lang-value { padding:3px 8px;border-radius:999px;background:rgba(255,255,255,.2);
  font-weight:700;min-width:36px;text-align:center; }

/* ── Hero ──────────────────────────────────────────────────────────────────── */
.hero { padding:0; }
.hero-shell { width:100vw;height:100vh;position:relative;overflow:hidden; }
.hero-media-layer { position:absolute;top:0;left:0;width:100%;z-index:0;background:#000;height:30vh; }
.hero-media-layer video { position:absolute;left:0;width:100%;height:100%;top:50px;
  object-fit:contain;object-position:center 20%; }
@media(min-width:600px) {
  .hero-media-layer { height:100%; }
  .hero-media-layer video { top:0;object-fit:cover;object-position:center; }
}
.hero-overlay { position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;
  background-color:rgba(0,0,0,.38);padding-top:64px;justify-content:center; }
@media(min-width:600px) { .hero-overlay { justify-content:flex-start;padding-top:15%; } }
.hero-content { width:90%;max-width:1000px;display:flex;flex-direction:column;
  align-items:center;justify-content:center;text-align:center; }
.hero-content h1 { margin:0 0 28px;font-size:1.8rem;color:white;line-height:1.15; }
.hero-content h2 { margin:0 0 52px;font-weight:400;font-size:1.1rem;line-height:1.55;
  color:rgba(255,255,255,.85);max-width:680px; }
@media(min-width:600px) { .hero-content h1 { font-size:2.5rem; } .hero-content h2 { font-size:1.3rem; } }
@media(min-width:768px) { .hero-content h1 { font-size:4rem; } .hero-content h2 { font-size:1.5rem; } }
.hero-cta { display:inline-flex;align-items:center;background:rgba(255,255,255,.2);color:white;
  backdrop-filter:blur(10px);border-radius:20px;padding:12px 28px;font-size:1.05rem;font-weight:700;
  box-shadow:0 4px 6px rgba(0,0,0,.1);transition:background .3s,transform .2s;
  border:1px solid rgba(255,255,255,.25); }
.hero-cta:hover { background:rgba(255,255,255,.3);transform:translateY(-1px); }
.hero-trusted { margin-top:36px;display:flex;flex-direction:column;align-items:center;gap:10px;color:white; }
.hero-trusted p { font-size:.875rem;opacity:.9; }
.hero-avatars { display:flex;flex-direction:row-reverse; }
.avatar-circle { width:40px;height:40px;border-radius:50%;border:2px solid #19191b;
  box-sizing:content-box;margin-left:-10px;opacity:.9; }
.avatar-circle:last-child { margin-left:0; }
.hero-quote { font-size:.85rem;color:rgba(255,255,255,.85);line-height:1.4;max-width:480px; }

/* ── Stats bar ─────────────────────────────────────────────────────────────── */
.stats-bar { background:var(--bg-soft);border-bottom:1px solid var(--border); }
.stats-inner { display:flex;align-items:center;justify-content:center;gap:0;padding:20px 24px;flex-wrap:wrap; }
.stat-item { display:flex;flex-direction:column;align-items:center;padding:0 40px; }
.stat-num { font-size:1.6rem;font-weight:700;background:var(--accent-gradient);
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;line-height:1.2; }
.stat-lbl { font-size:.8rem;color:var(--text-muted);margin-top:4px; }
.stat-div { width:1px;height:40px;background:var(--border); }
@media(max-width:600px) { .stat-div { display:none; } .stat-item { padding:12px 20px; } }

/* ── Sections ──────────────────────────────────────────────────────────────── */
section { padding:72px 0; }
.section-dark { background:var(--bg-soft); }
.section-light { background:transparent; }
.container { width:min(1180px,92vw);margin:0 auto; }
.section-header { display:flex;flex-direction:column;gap:10px;margin-bottom:36px;align-items:center;text-align:center; }
.section-header h2 { font-size:clamp(1.8rem,3vw,2.6rem); }
.section-header p { color:var(--text-muted);max-width:680px; }

/* ── Carousel ──────────────────────────────────────────────────────────────── */
.mv-carousel { position:relative;margin:0 auto 48px;width:min(900px,100%);display:flex;align-items:center;gap:12px; }
.carousel-track { overflow:hidden;border-radius:16px;border:1px solid rgba(255,255,255,.08);flex:1;background:#0e0e16; }
.carousel-slides { display:flex;transition:transform .4s ease; }
.carousel-slide { min-width:100%;display:grid;color:inherit; }
.slide-media { background:#0a0a10; }
.slide-media img { width:100%;height:auto;display:block; }
.slide-info { padding:16px 20px 20px;text-align:center; }
.slide-info h3 { margin-bottom:8px;font-size:1.05rem; }
.slide-info p { color:var(--text-muted);font-size:.9rem;line-height:1.5; }
.carousel-btn { width:40px;height:40px;border-radius:50%;border:1px solid rgba(255,255,255,.2);
  background:rgba(0,0,0,.35);color:white;font-size:1.6rem;display:inline-flex;align-items:center;
  justify-content:center;cursor:pointer;flex-shrink:0;transition:background .2s; }
.carousel-btn:hover { background:rgba(141,92,255,.3); }
.carousel-dots { position:absolute;bottom:-26px;left:50%;transform:translateX(-50%);display:flex;gap:8px; }
.carousel-dot { width:8px;height:8px;border-radius:50%;border:none;background:rgba(255,255,255,.3);cursor:pointer;padding:0; }
.carousel-dot.active { background:white; }
.feature-grid { display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:24px; }
.feature-card { padding:24px;border-radius:20px;border:1px solid var(--border);background:var(--card); }
.feature-card h3 { margin-bottom:12px;font-size:1.1rem; }
.feature-card p { color:var(--text-muted);font-size:.95rem;line-height:1.6; }
.feature-note { margin-top:16px;font-style:italic; }

/* ── ① Agent Pipeline ──────────────────────────────────────────────────────── */
.pipeline-flow { display:grid;grid-template-columns:repeat(7,auto);align-items:start;gap:0;overflow-x:auto; }
@media(max-width:900px) { .pipeline-flow { grid-template-columns:1fr;align-items:center; } }

.pipeline-agent {
  min-width:180px;padding:20px 18px;border-radius:16px;border:2px solid var(--border);
  background:var(--card);transition:border-color .4s,box-shadow .4s;position:relative;overflow:hidden; }
.pipeline-agent::before {
  content:'';position:absolute;inset:0;border-radius:14px;
  background:radial-gradient(ellipse at 50% 0%,var(--agent-color, #8d5cff) 0%,transparent 70%);
  opacity:0;transition:opacity .4s; }
.pipeline-agent.active { border-color:var(--agent-color, #8d5cff);
  box-shadow:0 0 28px -4px var(--agent-color, #8d5cff); }
.pipeline-agent.active::before { opacity:.12; }

.agent-index { font-size:.75rem;font-weight:700;color:var(--agent-color,#8d5cff);margin-bottom:8px;letter-spacing:.05em; }
.agent-name { font-size:.95rem;font-weight:700;margin-bottom:2px; }
.agent-sub { font-size:.75rem;color:var(--text-muted);margin-bottom:12px; }
.agent-outputs { list-style:none;padding:0;margin:0;display:flex;flex-direction:column;gap:5px; }
.agent-outputs li { font-size:.78rem;color:var(--text-muted);padding:4px 8px;
  background:rgba(255,255,255,.04);border-radius:6px;border:1px solid var(--border); }
.pipeline-agent.active .agent-outputs li { border-color:var(--agent-color,#8d5cff);opacity:.9; }

.pipeline-arrow { display:flex;flex-direction:column;align-items:center;justify-content:center;
  padding:0 8px;color:var(--text-muted);position:relative;min-width:48px;padding-top:24px; }
@media(max-width:900px) {
  .pipeline-arrow { padding:8px 0 0;min-width:unset;transform:rotate(90deg);margin:4px auto; } }
.pipeline-arrow svg { width:40px;height:12px; }
.arrow-dot { width:6px;height:6px;border-radius:50%;background:var(--text-muted);
  position:absolute;top:24px;left:50%;transform:translateX(-50%); }
.pipeline-arrow.flowing .arrow-dot { animation:dotFlow .6s ease-in-out forwards; }
@keyframes dotFlow {
  0%   { left:10%;opacity:1; }
  100% { left:90%;opacity:0; }
}

.pipeline-note { margin-top:28px;text-align:center;color:var(--text-muted);font-size:.88rem;
  max-width:660px;margin-left:auto;margin-right:auto; }

/* ── ② Music Analysis Demo ─────────────────────────────────────────────────── */
.music-demo { background:var(--card);border:1px solid var(--border);border-radius:20px;
  padding:28px 28px 20px;position:relative; }
.bpm-badge { display:inline-flex;align-items:baseline;gap:6px;
  background:linear-gradient(135deg,rgba(141,92,255,.2),rgba(243,178,255,.15));
  border:1px solid rgba(141,92,255,.4);border-radius:12px;padding:8px 16px;margin-bottom:20px; }
.bpm-num { font-size:2rem;font-weight:800;background:var(--accent-gradient);
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;line-height:1; }
.bpm-label { font-size:.85rem;color:var(--text-muted);font-weight:600; }

.waveform-wrap { position:relative;height:90px;margin-bottom:10px; }
.waveform { display:flex;align-items:flex-end;gap:2px;height:100%;padding:0 2px; }
.waveform-bar { flex:1;min-width:3px;background:linear-gradient(to top,#8d5cff,#f3b2ff);
  border-radius:2px 2px 0 0;transform-origin:bottom;animation:waveAnim 1.4s ease-in-out infinite alternate; }
@keyframes waveAnim {
  0%   { transform:scaleY(.25);opacity:.6; }
  100% { transform:scaleY(1);opacity:1; }
}
.playhead { position:absolute;top:0;bottom:0;width:2px;background:rgba(255,255,255,.7);
  border-radius:1px;pointer-events:none;box-shadow:0 0 8px rgba(255,255,255,.5); }

.segment-bar { display:flex;height:28px;border-radius:8px;overflow:hidden;gap:2px;margin-bottom:14px; }
.segment { display:flex;align-items:center;justify-content:center;border:1px solid;border-radius:6px;
  font-size:.68rem;font-weight:600;color:white;transition:opacity .2s; }

.lyrics-ticker { min-height:24px;text-align:center;font-size:.83rem;color:var(--text-muted);
  font-family:monospace;letter-spacing:.02em; }
.lyric-enter-active,.lyric-leave-active { transition:opacity .4s,transform .4s; }
.lyric-enter-from { opacity:0;transform:translateY(8px); }
.lyric-leave-to   { opacity:0;transform:translateY(-8px); }

/* ── ③ Model Matrix ────────────────────────────────────────────────────────── */
.model-tabs { display:flex;gap:8px;justify-content:center;margin-bottom:28px; }
.model-tab { padding:9px 24px;border-radius:999px;border:1px solid var(--border);
  background:transparent;color:var(--text-muted);font-size:.9rem;cursor:pointer;transition:all .2s; }
.model-tab.active { background:var(--accent-gradient);color:#000;border-color:transparent;font-weight:600; }
.model-tab:not(.active):hover { border-color:var(--accent);color:var(--text); }

.model-grid { display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:18px; }
.model-card { --mc: #8d5cff;padding:20px;border-radius:16px;border:1px solid var(--border);
  background:var(--card);display:flex;flex-direction:column;gap:8px;
  transition:border-color .25s,box-shadow .25s;position:relative;overflow:hidden; }
.model-card::before { content:'';position:absolute;top:0;left:0;right:0;height:2px;
  background:var(--mc);opacity:.7;border-radius:16px 16px 0 0; }
.model-card:hover { border-color:var(--mc);box-shadow:0 0 24px -6px var(--mc); }
.model-card-top { display:flex;align-items:center;justify-content:space-between;gap:8px; }
.model-name { font-size:1rem;font-weight:700; }
.model-badge { font-size:.7rem;font-weight:600;padding:3px 9px;border-radius:999px; }
.model-badge.open       { background:rgba(74,222,128,.15);color:#4ade80;border:1px solid rgba(74,222,128,.3); }
.model-badge.commercial { background:rgba(251,191,36,.12);color:#fbbf24;border:1px solid rgba(251,191,36,.25); }
.model-tag { font-size:.76rem;color:var(--mc);font-weight:700; }
.model-specs { display:flex;flex-wrap:wrap;gap:5px;margin:2px 0; }
.model-spec-chip { font-size:.68rem;padding:2px 8px;border-radius:999px;
  background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);color:var(--text-muted); }
.model-bestfor { font-size:.8rem;color:var(--text-muted);line-height:1.5;margin:0; }
.model-bestfor strong { color:var(--mc);font-weight:600; }
.model-desc { font-size:.83rem;color:var(--text-muted);line-height:1.55;margin:0; }

/* ── ④ Export Presets ──────────────────────────────────────────────────────── */
.export-grid { display:grid;grid-template-columns:repeat(auto-fill,minmax(168px,1fr));gap:16px; }
.export-card { padding:20px 16px;border-radius:16px;border:1px solid var(--border);background:var(--card);
  display:flex;flex-direction:column;align-items:center;gap:12px;text-align:center;
  transition:border-color .2s,transform .2s; }
.export-card:hover { border-color:color-mix(in srgb,var(--ep,#8d5cff) 50%,transparent);transform:translateY(-3px);
  box-shadow:0 6px 24px color-mix(in srgb,var(--ep,#8d5cff) 20%,transparent); }
.export-logo-wrap { display:flex;align-items:center;justify-content:center;height:56px;width:56px;
  border-radius:14px;background:color-mix(in srgb,var(--ep,#8d5cff) 12%,transparent);
  border:1px solid color-mix(in srgb,var(--ep,#8d5cff) 25%,transparent); }
.export-logo-svg { width:28px;height:28px; }
.export-name { font-size:.95rem;font-weight:700; }
.export-ratio { font-size:.78rem;color:var(--accent-strong);font-weight:600; }
.export-specs { font-size:.73rem;color:var(--text-muted); }

/* ── Testimonials ──────────────────────────────────────────────────────────── */
.testimonial-grid { display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:20px; }
.testimonial-card { padding:22px;border-radius:18px;border:1px solid var(--border);background:rgba(25,25,35,.7); }
.testimonial-header { display:flex;align-items:center;gap:12px;margin-bottom:14px; }
.testimonial-header h4 { font-size:1rem;margin-bottom:2px; }
.testimonial-header span { color:var(--text-muted);font-size:.82rem; }
.testimonial-card > p { color:var(--text-muted);font-size:.9rem;line-height:1.6; }

/* ── Gallery ───────────────────────────────────────────────────────────────── */
.gallery-grid { display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:20px; }
.gallery-tile { border-radius:18px;border:1px solid var(--border);overflow:hidden;background:#11111a; }
.gallery-tile-img { height:140px;width:100%; }
.gallery-tile > div { padding:12px 14px 16px; }
.gallery-tile span { display:block;font-size:.9rem;font-weight:500;margin-bottom:4px; }
.gallery-tile small { color:var(--text-muted);font-size:.8rem; }

/* ── News ──────────────────────────────────────────────────────────────────── */
.news-grid { display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px; }
.news-card { padding:22px;border-radius:18px;border:1px solid var(--border);background:var(--card); }
.news-card a { font-weight:600;font-size:.95rem;line-height:1.5;display:block;color:var(--text);transition:color .2s; }
.news-card a:hover { color:var(--accent); }
.news-card span { display:block;margin-top:14px;color:var(--text-muted);font-size:.85rem; }

/* ── FAQ ───────────────────────────────────────────────────────────────────── */
.faq-grid { display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px; }
.faq-card { padding:22px;border-radius:18px;border:1px solid var(--border);background:var(--card); }
.faq-card h3 { margin-bottom:12px;font-size:1rem; }
.faq-card p { color:var(--text-muted);font-size:.88rem;line-height:1.6; }

/* ── Footer ────────────────────────────────────────────────────────────────── */
.site-footer { padding:60px 0;border-top:1px solid var(--border);background:#050508; }
.footer-grid { display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:32px;color:var(--text-muted); }
.footer-logo { font-size:1.1rem;font-weight:700;background:var(--accent-gradient);
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:12px; }
.footer-grid > div > p { font-size:.88rem;line-height:1.6; }
.footer-grid h4 { margin-bottom:14px;color:var(--text);font-size:.95rem; }
.footer-grid ul { list-style:none;display:grid;gap:8px; }
.footer-grid li { font-size:.88rem; }
.footer-grid a { color:var(--text-muted);transition:color .2s; }
.footer-grid a:hover { color:var(--accent); }

/* ── App Preview ───────────────────────────────────────────────────────────── */
.app-preview-section { padding:72px 0; }
.app-preview-grid { display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:20px; }
.app-preview-card { display:block;border-radius:16px;overflow:hidden;border:1px solid var(--border);
  background:#0c0c18;transition:transform .25s,box-shadow .25s;cursor:pointer;color:inherit; }
.app-preview-card:hover { transform:translateY(-4px);box-shadow:0 12px 40px rgba(141,92,255,.25); }
.app-preview-card img { width:100%;display:block;aspect-ratio:16/9;object-fit:cover; }
.app-preview-label { padding:10px 14px;font-size:.88rem;font-weight:600;color:var(--text); }

/* ── Hero bg image fallback ────────────────────────────────────────────────── */
.hero-bg-img { position:absolute;left:0;top:0;width:100%;height:100%;object-fit:cover;object-position:center top;z-index:0; }
.hero-media-layer video { z-index:1; }

/* ── Feature card screenshot ───────────────────────────────────────────────── */
.feature-screenshot { width:100%;border-radius:10px;margin-bottom:16px;
  border:1px solid rgba(255,255,255,.07);display:block;
  box-shadow:0 4px 24px rgba(0,0,0,.4); }

/* ── Gallery tile icon & tag ───────────────────────────────────────────────── */
.gallery-tile-img { display:flex;flex-direction:column;align-items:center;justify-content:center;
  gap:10px;position:relative; }
.gallery-tile-icon { font-size:2.8rem;line-height:1;
  filter:drop-shadow(0 2px 10px rgba(0,0,0,.6)); }
.gallery-tile-tag { font-size:.7rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase;
  background:rgba(0,0,0,.45);color:rgba(255,255,255,.9);
  padding:3px 10px;border-radius:999px;backdrop-filter:blur(4px); }
.gallery-tile-meta { padding:12px 14px 16px; }
.gallery-tile-meta span { display:block;font-size:.9rem;font-weight:500;margin-bottom:4px; }
.gallery-tile-meta small { color:var(--text-muted);font-size:.8rem; }

/* ── Testimonial avatar initials ───────────────────────────────────────────── */
.t-avatar { width:42px;height:42px;border-radius:50%;display:flex;align-items:center;
  justify-content:center;font-size:1.05rem;font-weight:800;
  color:rgba(0,0,0,.75);flex-shrink:0;box-shadow:0 2px 8px rgba(0,0,0,.3); }

/* ── Mobile ────────────────────────────────────────────────────────────────── */
@media(max-width:600px) {
  .nav-links { display:none; }
  .lang-label-text { display:none; }
  .carousel-btn { display:none; }
}
</style>
