<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()

// ─── i18n ────────────────────────────────────────────────────────────────────
const lang = ref<'en' | 'zh'>('en')

const i18n = {
  en: {
    nav_gallery: 'Gallery',
    nav_create: 'Create',
    nav_signin: 'Sign In',
    lang_label: '语言 / Language',
    lang_current: 'EN',
    hero_title: 'The synthesizer for the music video world.',
    hero_subtitle: 'Multi-agent AI orchestration — from lyrics to final MV, in minutes.',
    hero_cta: 'Start creating now',
    hero_trusted: 'Used by 500+ creators in beta',
    hero_quote: '"AIMV Studio turned my concept into a full MV in under 20 minutes." — Beta User',
    music_videos_title: 'Music videos',
    ai_gen_title: 'AI-Generated Scenes',
    ai_gen_desc: 'Describe your vision and the Screenwriter Agent builds a shot-by-shot storyboard. Images and video clips are generated by Z-image, Wan2.2, and other top models. No shooting required. The unique look of your videos is guaranteed to captivate your audience.',
    multi_model_title: 'Multi-Model Pipeline',
    multi_model_desc: 'Switch between Seedance 2.0, Veo 3.1, Grok Video 1.0, and Wan2.2 14B. Each model has distinct strengths — choose per-shot or let the Director Agent decide for you.',
    multi_model_note: 'AIMV Studio feels like a professional NLE, but the entire timeline is written by AI.',
    how_it_works_title: 'How it works',
    how_plan_title: 'Plan',
    how_plan_desc: 'Chat with the AI director. Describe your mood, style, and story. A complete shot-by-shot storyboard is generated instantly by the Screenwriter Agent.',
    how_generate_title: 'Generate',
    how_generate_desc: 'Image, video, and music assets are generated in parallel by best-in-class AI models. The Director Agent selects the right model per shot automatically.',
    how_review_title: 'Review',
    how_review_desc: 'The Verifier Agent scores each generated clip 1–5. Low-quality shots are automatically retried up to 3 times. You can also compare A/B versions per shot.',
    how_export_title: 'Export',
    how_export_desc: 'One-click export with loudness normalization (−14 LUFS / EBU R128) and subtitle burning. Presets for Douyin, Bilibili, YouTube, Xiaohongshu, and more.',
    how_endless_title: 'End-to-End in Minutes',
    how_endless_desc: 'From concept to export-ready MV with full AI orchestration. Four specialized agents handle planning, generation, quality review, and composition — no manual editing required.',
    testimonials_title: 'What creators say',
    testimonials_subtitle: 'Creators in beta have produced over 10,000 AI-generated video clips with AIMV Studio.',
    t1_name: 'Lin Wei',
    t1_role: 'Indie Music Producer',
    t1_quote: 'AIMV Studio understood my style from just a few sentences. The storyboard nailed the mood, and the generated shots needed zero retouching.',
    t2_name: 'Zhao Ming',
    t2_role: 'Music Video Director',
    t2_quote: 'The multi-agent pipeline is genuinely impressive. I briefed it like I would a human team, and it delivered exactly what I envisioned.',
    t3_name: 'Sara K.',
    t3_role: 'Electronic Artist',
    t3_quote: "I've tried every AI video tool out there. AIMV Studio is the only one that truly treats the music as the real driver of the visuals.",
    t4_name: 'Chen Jie',
    t4_role: 'Singer-Songwriter',
    t4_quote: 'The BPM-synced cuts and automatic loudness normalization to −14 LUFS saved me hours of post-production work.',
    t5_name: 'Alex Turner',
    t5_role: 'Visual Artist & Director',
    t5_quote: 'Character consistency across 20+ shots was something I thought would break any AI. AIMV Studio held up perfectly the whole way through.',
    t6_name: 'Wang Fang',
    t6_role: 'Content Creator',
    t6_quote: 'From a single description to a fully exported MV in just 18 minutes. I was genuinely shocked by the quality.',
    what_you_create_title: 'What you could create',
    what_you_create_subtitle: 'AI-generated music videos with unlimited style variety.',
    powered_by_title: 'Powered by',
    news_title: 'News & Updates',
    news_1: 'AIMV Studio 1.0: Full multi-agent MV generation pipeline now available',
    news_2: 'Wan2.2 14B integration: Open-source 4K video generation with Apache 2.0 license',
    news_3: 'Real audio segmentation: MFCC + agglomerative clustering for beat-perfect video cuts',
    news_date_1: '2025/03/15',
    news_date_2: '2025/02/28',
    news_date_3: '2025/01/20',
    faq_title: 'Frequently asked questions',
    faq_1_q: 'What is AIMV Studio?',
    faq_1_a: 'AIMV Studio is an AI-powered music video creation platform. Four specialized agents — Screenwriter, Director, Music Producer, and Verifier — collaborate to plan, generate, and review every shot in your MV.',
    faq_2_q: 'Who owns the rights to generated videos?',
    faq_2_a: 'You have complete ownership of all videos you create with AIMV Studio. We claim zero rights to your content and never use your videos without explicit permission.',
    faq_3_q: 'Which AI models are supported?',
    faq_3_a: 'AIMV Studio supports Z-image for images; Wan2.2 14B, Seedance 2.0, Veo 3.1, and Grok Video 1.0 for video; and ACEStep 1.5, Suno, and Google Lyria for music generation.',
    faq_4_q: 'How does music analysis work?',
    faq_4_a: 'We use librosa for BPM and beat detection, MFCC + chroma features with agglomerative clustering for structure segmentation (intro / verse / chorus / bridge / outro), and faster-whisper for lyrics transcription — all used to sync video cuts to your music.',
    features_title: 'Platform Capabilities',
    feat_1: 'Beat-Synced Video Cuts',
    feat_2: 'Lyrics-to-Subtitle Export',
    feat_3: 'Cross-Shot Character Consistency',
    feat_4: '−14 LUFS Loudness Normalization',
    feat_5: 'Multi-Platform Export Presets',
    feat_6: 'A/B Shot Comparison',
    feat_7: 'SRT Subtitle Burn-In',
    feat_8: '5-Model Video Selection',
    footer_tagline: 'Built by students who love AI and music. Open-source, community-driven.',
    footer_product: 'Product',
    footer_p1: 'Create',
    footer_p2: 'Gallery',
    footer_p3: 'My Projects',
    footer_p4: 'API Docs',
    footer_models: 'AI Models',
    footer_m1: 'Z-image',
    footer_m2: 'Wan2.2 14B',
    footer_m3: 'Seedance 2.0',
    footer_m4: 'ACEStep 1.5',
    footer_more: 'More',
    footer_more1: 'GitHub',
    footer_more2: 'Documentation',
    footer_more3: 'About',
    footer_more4: 'Open Source',
    footer_socials: 'Community',
    footer_s1: 'GitHub',
    footer_s2: 'Discord',
    footer_s3: 'Bilibili',
    footer_s4: 'Twitter / X',
  },
  zh: {
    nav_gallery: '作品库',
    nav_create: '开始创作',
    nav_signin: '登录',
    lang_label: '语言 / Language',
    lang_current: '中文',
    hero_title: '为音乐视频世界打造的合成器。',
    hero_subtitle: '多智能体 AI 编排 — 从歌词到成品 MV，仅需数分钟。',
    hero_cta: '立即开始创作',
    hero_trusted: '500+ 位创作者已加入内测',
    hero_quote: '"AIMV Studio 在 20 分钟内将我的创意变成了完整 MV。" — 内测用户',
    music_videos_title: '音乐视频',
    ai_gen_title: 'AI 生成分镜',
    ai_gen_desc: '描述你的创意，编剧 Agent 自动生成逐镜分镜脚本。图像与视频片段由 Z-image、Wan2.2 等顶尖模型生成，无需拍摄。独特的视觉风格将吸引你的观众。',
    multi_model_title: '多模型管线',
    multi_model_desc: '可在 Seedance 2.0、Veo 3.1、Grok Video 1.0 和 Wan2.2 14B 之间切换。每个模型各有优势 — 按镜头选择或由导演 Agent 自动决策。',
    multi_model_note: 'AIMV Studio 像一个专业剪辑软件，但整条时间轴由 AI 撰写。',
    how_it_works_title: '如何运作',
    how_plan_title: '规划',
    how_plan_desc: '与 AI 导演对话，描述你的风格与故事。编剧 Agent 即时生成完整的逐镜分镜脚本。',
    how_generate_title: '生成',
    how_generate_desc: '图像、视频、音乐资产由顶级 AI 模型并行生成。导演 Agent 自动为每个镜头选择最佳模型，全程无需干预。',
    how_review_title: '审核',
    how_review_desc: '审核 Agent 对每个生成片段进行 1–5 分质量评分，低质量镜头自动重试，最多 3 次。你也可以逐镜进行 A/B 版本对比。',
    how_export_title: '导出',
    how_export_desc: '一键导出，自动完成响度标准化（−14 LUFS / EBU R128）和字幕烧录，支持抖音、Bilibili、YouTube、小红书等预设。',
    how_endless_title: '分钟级端到端生产',
    how_endless_desc: '从创意到可发布 MV，由四个专业 Agent 全自动完成规划、生成、审核与合成 — 无需手动剪辑。',
    testimonials_title: '创作者评价',
    testimonials_subtitle: '内测创作者已使用 AIMV Studio 生成超过 10,000 个 AI 视频片段。',
    t1_name: '林威',
    t1_role: '独立音乐制作人',
    t1_quote: 'AIMV Studio 仅凭几句描述就理解了我的风格，分镜脚本完美还原了情绪，生成的镜头几乎不需要任何修改。',
    t2_name: '赵明',
    t2_role: 'MV 导演',
    t2_quote: '多智能体管线让我印象深刻。我像对待真实团队一样给它简报，它真的交付了我想要的东西。',
    t3_name: 'Sara K.',
    t3_role: '电子音乐艺术家',
    t3_quote: '我试过所有 AI 视频工具，AIMV Studio 是唯一一个真正以音乐为驱动的系统。',
    t4_name: '陈洁',
    t4_role: '创作歌手',
    t4_quote: 'BPM 同步剪辑和自动响度标准化（−14 LUFS）为我节省了大量后期时间。',
    t5_name: 'Alex Turner',
    t5_role: '视觉艺术家 / 导演',
    t5_quote: '20+ 个镜头之间的角色一致性，我以为会让任何 AI 崩溃。AIMV Studio 全程表现完美。',
    t6_name: '王芳',
    t6_role: '内容创作者',
    t6_quote: '从一句描述到导出成品 MV 只用了 18 分钟，质量让我真的很震惊。',
    what_you_create_title: '你可以创作的内容',
    what_you_create_subtitle: '拥有无限风格多样性的 AI 生成音乐视频。',
    powered_by_title: '技术支持',
    news_title: '新闻与更新',
    news_1: 'AIMV Studio 1.0：完整多智能体 MV 生成管线正式上线',
    news_2: 'Wan2.2 14B 集成：Apache 2.0 授权的开源 4K 视频生成能力',
    news_3: '真实音频分段：MFCC + 聚类实现节拍精准剪辑',
    news_date_1: '2025/03/15',
    news_date_2: '2025/02/28',
    news_date_3: '2025/01/20',
    faq_title: '常见问题',
    faq_1_q: '什么是 AIMV Studio？',
    faq_1_a: 'AIMV Studio 是 AI 驱动的音乐视频创作平台。四个专业 Agent — 编剧、导演、音乐制作人和审核员 — 协作完成 MV 的规划、生成与审核。',
    faq_2_q: '我拥有生成视频的版权吗？',
    faq_2_a: '你对所有通过 AIMV Studio 创建的视频拥有完整版权。我们不主张任何权益，也不会在未经许可的情况下使用你的内容。',
    faq_3_q: '支持哪些 AI 模型？',
    faq_3_a: 'AIMV Studio 支持 Z-image 生图；Wan2.2 14B、Seedance 2.0、Veo 3.1、Grok Video 1.0 生视频；ACEStep 1.5、Suno、Google Lyria 生成音乐。',
    faq_4_q: '音乐分析如何工作？',
    faq_4_a: '使用 librosa 进行 BPM 和节拍检测，MFCC + chroma 特征结合层次聚类实现结构分段（intro / verse / chorus / bridge / outro），faster-whisper 转录歌词 — 全部用于将视频剪辑同步至音乐节拍。',
    features_title: '平台能力',
    feat_1: '节拍同步视频剪辑',
    feat_2: '歌词转字幕导出',
    feat_3: '跨镜头角色一致性',
    feat_4: '−14 LUFS 响度标准化',
    feat_5: '多平台导出预设',
    feat_6: 'A/B 镜头对比',
    feat_7: 'SRT 字幕烧录',
    feat_8: '5 款视频模型可选',
    footer_tagline: '由热爱 AI 与音乐的学生构建，开源，社区驱动。',
    footer_product: '产品',
    footer_p1: '开始创作',
    footer_p2: '作品库',
    footer_p3: '我的项目',
    footer_p4: 'API 文档',
    footer_models: 'AI 模型',
    footer_m1: 'Z-image',
    footer_m2: 'Wan2.2 14B',
    footer_m3: 'Seedance 2.0',
    footer_m4: 'ACEStep 1.5',
    footer_more: '更多',
    footer_more1: 'GitHub',
    footer_more2: '文档',
    footer_more3: '关于',
    footer_more4: '开源',
    footer_socials: '社区',
    footer_s1: 'GitHub',
    footer_s2: 'Discord',
    footer_s3: 'Bilibili',
    footer_s4: 'Twitter / X',
  },
} as const

type LangKey = keyof typeof i18n.en
const t = computed(() => i18n[lang.value] as Record<LangKey, string>)

function toggleLang() {
  lang.value = lang.value === 'en' ? 'zh' : 'en'
  localStorage.setItem('lang', lang.value)
  document.documentElement.lang = lang.value === 'zh' ? 'zh-CN' : 'en'
}

// ─── routing ─────────────────────────────────────────────────────────────────
function startCreating() {
  const token = localStorage.getItem('token')
  router.push(token ? '/create' : '/login')
}

// ─── carousel ────────────────────────────────────────────────────────────────
interface SlideItem {
  url: string
  title: string
  desc: string
  pic: string
}

const videoSources = [
  {
    bvid: 'BV1xjvvBwEZq',
    url: 'https://www.bilibili.com/video/BV1xjvvBwEZq/',
    fallback: {
      title: '大二期末作品MV《几分之几》',
      desc: '感谢真诚的影像，汇集每一个真诚创作的你。第一次和好朋友担任主创创作的作品，中间少不了无数朋友们的帮助。',
      pic: 'https://i1.hdslb.com/bfs/archive/b9316f0f07d2b17a5c9cf2231a570f27ade30e9e.jpg',
    },
  },
  {
    bvid: 'BV1gpyGBwEie',
    url: 'https://www.bilibili.com/video/BV1gpyGBwEie/',
    fallback: {
      title: '他不懂（RNB版）',
      desc: '当rnb碰到张杰的《他不懂》',
      pic: 'https://i0.hdslb.com/bfs/archive/395908458c09a21a72da46fec62f0abaab910e8b.jpg',
    },
  },
  {
    bvid: 'BV1psQ8YfEXU',
    url: 'https://www.bilibili.com/video/BV1psQ8YfEXU/',
    fallback: {
      title: '【4K60FPS】IU李知恩《Blueming》超甜美现场！',
      desc: '官方现场。IU真的很可爱，长得漂亮，演技也挺棒的，这首《Blueming》是IU很经典的一首歌曲。',
      pic: 'https://i1.hdslb.com/bfs/archive/cb3efec92dfe0c03f262e88bf2b7a7b4daa47b52.jpg',
    },
  },
]

const slides = ref<SlideItem[]>(videoSources.map(s => ({ url: s.url, ...s.fallback })))
const activeIndex = ref(0)
let carouselTimer: ReturnType<typeof setInterval> | null = null

function goTo(index: number) {
  activeIndex.value = ((index % slides.value.length) + slides.value.length) % slides.value.length
}
function prevSlide() { goTo(activeIndex.value - 1); restartTimer() }
function nextSlide() { goTo(activeIndex.value + 1); restartTimer() }
function dotClick(i: number) { goTo(i); restartTimer() }

function startTimer() {
  carouselTimer = setInterval(() => goTo(activeIndex.value + 1), 5000)
}
function stopTimer() {
  if (carouselTimer) { clearInterval(carouselTimer); carouselTimer = null }
}
function restartTimer() { stopTimer(); startTimer() }

async function fetchSlide(source: typeof videoSources[0]): Promise<SlideItem> {
  try {
    const res = await fetch(`https://api.bilibili.com/x/web-interface/view?bvid=${source.bvid}`)
    const json = await res.json()
    if (json.code !== 0) throw new Error('bad response')
    const d = json.data
    return {
      url: source.url,
      title: String(d.title || source.fallback.title).replace(/[<>]/g, '').trim(),
      desc: String(d.desc || source.fallback.desc).replace(/[<>]/g, '').trim(),
      pic: d.pic?.startsWith('http') ? d.pic : source.fallback.pic,
    }
  } catch {
    return { url: source.url, ...source.fallback }
  }
}

// ─── static data ─────────────────────────────────────────────────────────────
const galleryItems = [
  { title: 'K-Pop Visual Edit', artist: 'Cyberpunk style', bg: 'linear-gradient(135deg,#ff6b9d,#c051e0)' },
  { title: 'Chinese Classical', artist: 'Traditional ink', bg: 'linear-gradient(135deg,#2d5016,#8b6914)' },
  { title: 'Indie Film Aesthetic', artist: 'Golden hour', bg: 'linear-gradient(135deg,#3a3a3a,#8b7355)' },
  { title: 'Electronic Dance', artist: 'Neon club scene', bg: 'linear-gradient(135deg,#00e5ff,#aa00ff)' },
  { title: 'Urban R&B', artist: 'Street photography', bg: 'linear-gradient(135deg,#667eea,#764ba2)' },
  { title: 'Fantasy Epic', artist: 'Cinematic orchestral', bg: 'linear-gradient(135deg,#a18cd1,#fbc2eb)' },
]

const poweredBy = [
  'Z-image', 'Wan2.2 14B', 'Seedance 2.0', 'Veo 3.1',
  'Grok Video 1.0', 'ACEStep 1.5', 'Suno', 'Google Lyria',
  'GPT-4o', 'Gemini 2.5 Flash', 'htdemucs', 'faster-whisper',
]

const avatarColors = ['#8d5cff', '#f3b2ff', '#5cf3ff', '#ff9bd1', '#ffcf5c']

const testimonials = computed(() => [
  { name: t.value.t1_name, role: t.value.t1_role, quote: t.value.t1_quote },
  { name: t.value.t2_name, role: t.value.t2_role, quote: t.value.t2_quote },
  { name: t.value.t3_name, role: t.value.t3_role, quote: t.value.t3_quote },
  { name: t.value.t4_name, role: t.value.t4_role, quote: t.value.t4_quote },
  { name: t.value.t5_name, role: t.value.t5_role, quote: t.value.t5_quote },
  { name: t.value.t6_name, role: t.value.t6_role, quote: t.value.t6_quote },
])

const features = computed(() => [
  t.value.feat_1, t.value.feat_2, t.value.feat_3, t.value.feat_4,
  t.value.feat_5, t.value.feat_6, t.value.feat_7, t.value.feat_8,
])

onMounted(() => {
  const stored = localStorage.getItem('lang')
  if (stored === 'en' || stored === 'zh') {
    lang.value = stored
  } else if ((navigator.language || '').toLowerCase().startsWith('zh')) {
    lang.value = 'zh'
  }
  Promise.all(videoSources.map(fetchSlide)).then(items => { slides.value = items })
  startTimer()
})

onUnmounted(() => stopTimer())
</script>

<template>
  <div class="home-page">

    <!-- ─── HEADER ─────────────────────────────────────────────────────── -->
    <header class="site-header">
      <div class="header-inner">
        <router-link to="/" class="logo">
          <span class="logo-text">AIMV Studio</span>
        </router-link>
        <nav class="nav-links">
          <router-link to="/gallery">{{ t.nav_gallery }}</router-link>
          <a href="#" @click.prevent="startCreating">{{ t.nav_create }}</a>
          <router-link to="/login">{{ t.nav_signin }}</router-link>
        </nav>
        <button class="lang-toggle" type="button" @click="toggleLang" :aria-label="t.lang_label">
          <span class="lang-label-text">{{ t.lang_label }}</span>
          <span class="lang-value">{{ t.lang_current }}</span>
        </button>
      </div>
    </header>

    <main>

      <!-- ─── HERO ───────────────────────────────────────────────────────── -->
      <section class="hero">
        <div class="hero-shell">
          <div class="hero-media-layer" aria-hidden="true">
            <video src="/hero.mp4" autoplay muted loop playsinline></video>
          </div>
          <div class="hero-overlay">
            <div class="hero-content">
              <h1>{{ t.hero_title }}</h1>
              <h2>{{ t.hero_subtitle }}</h2>
              <a class="hero-cta" href="#" @click.prevent="startCreating">{{ t.hero_cta }}</a>
              <div class="hero-trusted">
                <p>{{ t.hero_trusted }}</p>
                <div class="hero-avatars">
                  <div
                    v-for="(color, i) in avatarColors"
                    :key="i"
                    class="avatar-circle"
                    :style="{ background: color }"
                  ></div>
                </div>
                <div class="hero-quote">{{ t.hero_quote }}</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- ─── MUSIC VIDEOS ───────────────────────────────────────────────── -->
      <section id="music-videos" class="section-dark">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.music_videos_title }}</h2>
          </div>
          <div
            class="mv-carousel"
            @mouseenter="stopTimer"
            @mouseleave="startTimer"
          >
            <button class="carousel-btn prev" type="button" @click="prevSlide" aria-label="Previous slide">&#8249;</button>
            <div class="carousel-track">
              <div class="carousel-slides" :style="{ transform: `translateX(-${activeIndex * 100}%)` }">
                <a
                  v-for="(slide, idx) in slides"
                  :key="idx"
                  class="carousel-slide"
                  :href="slide.url"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <div class="slide-media">
                    <img :src="slide.pic" :alt="slide.title" loading="lazy" />
                  </div>
                  <div class="slide-info">
                    <h3>{{ slide.title }}</h3>
                    <p>{{ slide.desc }}</p>
                  </div>
                </a>
              </div>
            </div>
            <button class="carousel-btn next" type="button" @click="nextSlide" aria-label="Next slide">&#8250;</button>
            <div class="carousel-dots">
              <button
                v-for="(_, idx) in slides"
                :key="idx"
                type="button"
                class="carousel-dot"
                :class="{ active: idx === activeIndex }"
                :aria-label="`Go to slide ${idx + 1}`"
                @click="dotClick(idx)"
              ></button>
            </div>
          </div>
          <div class="feature-grid">
            <article class="feature-card">
              <h3>{{ t.ai_gen_title }}</h3>
              <p>{{ t.ai_gen_desc }}</p>
            </article>
            <article class="feature-card">
              <h3>{{ t.multi_model_title }}</h3>
              <p>{{ t.multi_model_desc }}</p>
              <p class="feature-note">{{ t.multi_model_note }}</p>
            </article>
          </div>
        </div>
      </section>

      <!-- ─── HOW IT WORKS ───────────────────────────────────────────────── -->
      <section id="how-it-works" class="section-light">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.how_it_works_title }}</h2>
          </div>
          <div class="workflow-grid">
            <article class="workflow-card">
              <h3>{{ t.how_plan_title }}</h3>
              <p>{{ t.how_plan_desc }}</p>
            </article>
            <article class="workflow-card">
              <h3>{{ t.how_generate_title }}</h3>
              <p>{{ t.how_generate_desc }}</p>
            </article>
            <article class="workflow-card">
              <h3>{{ t.how_review_title }}</h3>
              <p>{{ t.how_review_desc }}</p>
            </article>
            <article class="workflow-card">
              <h3>{{ t.how_export_title }}</h3>
              <p>{{ t.how_export_desc }}</p>
            </article>
          </div>
          <div class="highlight-card">
            <h3>{{ t.how_endless_title }}</h3>
            <p>{{ t.how_endless_desc }}</p>
          </div>
        </div>
      </section>

      <!-- ─── TESTIMONIALS ───────────────────────────────────────────────── -->
      <section class="testimonials section-dark">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.testimonials_title }}</h2>
            <p>{{ t.testimonials_subtitle }}</p>
          </div>
          <div class="testimonial-grid">
            <article class="testimonial-card" v-for="item in testimonials" :key="item.name">
              <div class="testimonial-header">
                <div>
                  <h4>{{ item.name }}</h4>
                  <span>{{ item.role }}</span>
                </div>
              </div>
              <p>{{ item.quote }}</p>
            </article>
          </div>
        </div>
      </section>

      <!-- ─── GALLERY ────────────────────────────────────────────────────── -->
      <section id="what-you-create" class="section-light">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.what_you_create_title }}</h2>
            <p>{{ t.what_you_create_subtitle }}</p>
          </div>
          <div class="gallery-grid">
            <div class="gallery-tile" v-for="item in galleryItems" :key="item.title">
              <div class="gallery-tile-img" :style="{ background: item.bg }"></div>
              <div>
                <span>{{ item.title }}</span>
                <small>{{ item.artist }}</small>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- ─── POWERED BY ─────────────────────────────────────────────────── -->
      <section class="powered-by section-dark">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.powered_by_title }}</h2>
          </div>
          <div class="powered-grid">
            <span v-for="name in poweredBy" :key="name" class="powered-badge">{{ name }}</span>
          </div>
        </div>
      </section>

      <!-- ─── NEWS ───────────────────────────────────────────────────────── -->
      <section id="blog" class="section-light">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.news_title }}</h2>
          </div>
          <div class="news-grid">
            <article class="news-card">
              <a href="#">{{ t.news_1 }}</a>
              <span>{{ t.news_date_1 }}</span>
            </article>
            <article class="news-card">
              <a href="#">{{ t.news_2 }}</a>
              <span>{{ t.news_date_2 }}</span>
            </article>
            <article class="news-card">
              <a href="#">{{ t.news_3 }}</a>
              <span>{{ t.news_date_3 }}</span>
            </article>
          </div>
        </div>
      </section>

      <!-- ─── FAQ ────────────────────────────────────────────────────────── -->
      <section id="faq" class="faq section-dark">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.faq_title }}</h2>
          </div>
          <div class="faq-grid">
            <article class="faq-card">
              <h3>{{ t.faq_1_q }}</h3>
              <p>{{ t.faq_1_a }}</p>
            </article>
            <article class="faq-card">
              <h3>{{ t.faq_2_q }}</h3>
              <p>{{ t.faq_2_a }}</p>
            </article>
            <article class="faq-card">
              <h3>{{ t.faq_3_q }}</h3>
              <p>{{ t.faq_3_a }}</p>
            </article>
            <article class="faq-card">
              <h3>{{ t.faq_4_q }}</h3>
              <p>{{ t.faq_4_a }}</p>
            </article>
          </div>
        </div>
      </section>

      <!-- ─── FEATURES / CAPABILITIES ───────────────────────────────────── -->
      <section class="free-tools section-light">
        <div class="container">
          <div class="section-header">
            <h2>{{ t.features_title }}</h2>
          </div>
          <div class="tag-grid">
            <span v-for="feat in features" :key="feat">{{ feat }}</span>
          </div>
        </div>
      </section>

    </main>

    <!-- ─── FOOTER ─────────────────────────────────────────────────────── -->
    <footer class="site-footer">
      <div class="container footer-grid">
        <div>
          <div class="footer-logo">AIMV Studio</div>
          <p>{{ t.footer_tagline }}</p>
        </div>
        <div>
          <h4>{{ t.footer_product }}</h4>
          <ul>
            <li><a href="#" @click.prevent="startCreating">{{ t.footer_p1 }}</a></li>
            <li><router-link to="/gallery">{{ t.footer_p2 }}</router-link></li>
            <li><router-link to="/projects">{{ t.footer_p3 }}</router-link></li>
            <li><a href="#">{{ t.footer_p4 }}</a></li>
          </ul>
        </div>
        <div>
          <h4>{{ t.footer_models }}</h4>
          <ul>
            <li>{{ t.footer_m1 }}</li>
            <li>{{ t.footer_m2 }}</li>
            <li>{{ t.footer_m3 }}</li>
            <li>{{ t.footer_m4 }}</li>
          </ul>
        </div>
        <div>
          <h4>{{ t.footer_socials }}</h4>
          <ul>
            <li><a href="#">{{ t.footer_s1 }}</a></li>
            <li><a href="#">{{ t.footer_s2 }}</a></li>
            <li><a href="#">{{ t.footer_s3 }}</a></li>
            <li><a href="#">{{ t.footer_s4 }}</a></li>
          </ul>
        </div>
      </div>
    </footer>

  </div>
</template>

<style scoped>
/* ─── Reset & base ────────────────────────────────────────────────────────── */
.home-page {
  min-height: 100vh;
  font-family: "Geist", "Inter", system-ui, -apple-system, sans-serif;
}

.home-page a {
  color: inherit;
  text-decoration: none;
}

/* ─── Header ──────────────────────────────────────────────────────────────── */
.site-header {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  background-color: #121212;
  box-shadow: 0 2px 4px -1px rgba(0,0,0,.2), 0 4px 5px 0 rgba(0,0,0,.14), 0 1px 10px 0 rgba(0,0,0,.12);
  background-image: linear-gradient(rgba(255,255,255,.09), rgba(255,255,255,.09));
  z-index: 100;
}

.header-inner {
  display: flex;
  align-items: center;
  padding: 0 24px;
  min-height: 64px;
  margin: 0 auto;
  width: min(1180px, 92vw);
  gap: 24px;
}

.logo {
  display: flex;
  align-items: center;
  gap: 8px;
  color: var(--text) !important;
}

.logo-text {
  font-size: 18px;
  font-weight: 700;
  background: var(--accent-gradient);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  white-space: nowrap;
}

.nav-links {
  display: flex;
  gap: 20px;
  color: var(--text-muted);
  font-size: 0.9rem;
}

.nav-links a {
  color: var(--text-muted);
  transition: color 0.2s;
}

.nav-links a:hover {
  color: var(--text);
}

.lang-toggle {
  margin-left: auto;
  padding: 8px 14px;
  border-radius: 12px;
  border: 1px solid rgba(255,255,255,.4);
  background: linear-gradient(135deg, rgba(255,255,255,.15), rgba(141,92,255,.2));
  color: white;
  font-size: 0.875rem;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  gap: 8px;
  box-shadow: 0 4px 10px rgba(0,0,0,.25);
  white-space: nowrap;
  flex-shrink: 0;
}

.lang-label-text {
  font-weight: 600;
  letter-spacing: 0.3px;
}

.lang-value {
  padding: 3px 8px;
  border-radius: 999px;
  background: rgba(255,255,255,.2);
  font-weight: 700;
  min-width: 36px;
  text-align: center;
}

/* ─── Hero ────────────────────────────────────────────────────────────────── */
.hero {
  padding: 0;
}

.hero-shell {
  width: 100vw;
  height: 100vh;
  position: relative;
  overflow: hidden;
}

.hero-media-layer {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  z-index: 0;
  background-color: #000;
  height: 30vh;
}

.hero-media-layer video {
  position: absolute;
  left: 0;
  width: 100%;
  height: 100%;
  top: 50px;
  object-fit: contain;
  object-position: center 20%;
}

@media (min-width: 600px) {
  .hero-media-layer {
    height: 100%;
  }
  .hero-media-layer video {
    top: 0;
    object-fit: cover;
    object-position: center;
  }
}

.hero-overlay {
  position: absolute;
  inset: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: rgba(0,0,0,.35);
  padding-top: 64px;
  justify-content: center;
}

@media (min-width: 600px) {
  .hero-overlay {
    justify-content: flex-start;
    padding-top: 15%;
  }
}

.hero-content {
  width: 90%;
  max-width: 1000px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
}

.hero-content h1 {
  margin: 0 0 28px;
  font-size: 1.8rem;
  color: white;
  line-height: 1.15;
}

.hero-content h2 {
  margin: 0 0 56px;
  font-weight: 400;
  font-size: 1.15rem;
  line-height: 1.5;
  color: rgba(255,255,255,.85);
  max-width: 700px;
}

@media (min-width: 600px) {
  .hero-content h1 { font-size: 2.5rem; }
  .hero-content h2 { font-size: 1.3rem; }
}

@media (min-width: 768px) {
  .hero-content h1 { font-size: 4rem; }
  .hero-content h2 { font-size: 1.5rem; }
}

.hero-cta {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background-color: rgba(255,255,255,.2);
  color: white;
  backdrop-filter: blur(10px);
  border-radius: 20px;
  padding: 12px 28px;
  font-size: 1.05rem;
  font-weight: 700;
  box-shadow: 0 4px 6px rgba(0,0,0,.1);
  transition: background-color 0.3s ease, transform 0.2s ease;
  border: 1px solid rgba(255,255,255,.25);
}

.hero-cta:hover {
  background-color: rgba(255,255,255,.3);
  transform: translateY(-1px);
}

.hero-trusted {
  margin-top: 36px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 10px;
  color: white;
}

.hero-trusted p {
  font-size: 0.875rem;
  opacity: 0.9;
}

.hero-avatars {
  display: flex;
  flex-direction: row-reverse;
  align-items: center;
}

.avatar-circle {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  border: 2px solid #19191b;
  box-sizing: content-box;
  margin-left: -10px;
  opacity: 0.9;
}

.avatar-circle:last-child {
  margin-left: 0;
}

.hero-quote {
  font-size: 0.85rem;
  color: rgba(255,255,255,.85);
  line-height: 1.4;
  max-width: 480px;
}

/* ─── Sections ────────────────────────────────────────────────────────────── */
section {
  padding: 72px 0;
}

.section-dark {
  background: var(--bg-soft);
}

.section-light {
  background: transparent;
}

.container {
  width: min(1180px, 92vw);
  margin: 0 auto;
}

.section-header {
  display: flex;
  flex-direction: column;
  gap: 10px;
  margin-bottom: 36px;
  align-items: center;
  text-align: center;
}

.section-header h2 {
  font-size: clamp(1.8rem, 3vw, 2.6rem);
}

.section-header p {
  color: var(--text-muted);
  max-width: 680px;
  margin: 0 auto;
}

/* ─── Carousel ────────────────────────────────────────────────────────────── */
.mv-carousel {
  position: relative;
  margin: 0 auto 48px;
  width: min(900px, 100%);
  display: flex;
  align-items: center;
  gap: 12px;
}

.carousel-track {
  overflow: hidden;
  border-radius: 16px;
  border: 1px solid rgba(255,255,255,.08);
  flex: 1;
  background: #0e0e16;
}

.carousel-slides {
  display: flex;
  transition: transform 0.4s ease;
}

.carousel-slide {
  min-width: 100%;
  display: grid;
  color: inherit;
}

.slide-media {
  background: #0a0a10;
}

.slide-media img {
  width: 100%;
  height: auto;
  display: block;
}

.slide-info {
  padding: 16px 20px 20px;
  text-align: center;
}

.slide-info h3 {
  margin-bottom: 8px;
  font-size: 1.05rem;
}

.slide-info p {
  color: var(--text-muted);
  font-size: 0.9rem;
  line-height: 1.5;
}

.carousel-btn {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  border: 1px solid rgba(255,255,255,.2);
  background: rgba(0,0,0,.35);
  color: white;
  font-size: 1.6rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  flex-shrink: 0;
  transition: background 0.2s;
}

.carousel-btn:hover {
  background: rgba(141,92,255,.3);
}

.carousel-dots {
  position: absolute;
  bottom: -26px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  gap: 8px;
}

.carousel-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  border: none;
  background: rgba(255,255,255,.3);
  cursor: pointer;
  padding: 0;
  transition: background 0.2s;
}

.carousel-dot.active {
  background: white;
}

/* ─── Feature cards ───────────────────────────────────────────────────────── */
.feature-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 24px;
}

.feature-card {
  padding: 24px;
  border-radius: 20px;
  border: 1px solid var(--border);
  background: var(--card);
}

.feature-card h3 {
  margin-bottom: 12px;
  font-size: 1.1rem;
}

.feature-card p {
  color: var(--text-muted);
  font-size: 0.95rem;
  line-height: 1.6;
}

.feature-note {
  margin-top: 16px;
  color: var(--text-muted);
  font-style: italic;
}

/* ─── Workflow ────────────────────────────────────────────────────────────── */
.workflow-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(230px, 1fr));
  gap: 20px;
}

.workflow-card {
  padding: 24px;
  border-radius: 18px;
  border: 1px solid var(--border);
  background: var(--card);
}

.workflow-card h3 {
  margin-bottom: 12px;
  font-size: 1.05rem;
  color: var(--accent);
}

.workflow-card p {
  color: var(--text-muted);
  font-size: 0.9rem;
  line-height: 1.6;
}

.highlight-card {
  margin-top: 24px;
  padding: 28px;
  border-radius: 22px;
  border: 1px solid var(--border);
  background: linear-gradient(135deg, rgba(210,123,255,.16), rgba(255,155,209,.15));
}

.highlight-card h3 {
  margin-bottom: 10px;
  font-size: 1.2rem;
}

.highlight-card p {
  color: var(--text-muted);
  font-size: 0.95rem;
}

/* ─── Testimonials ────────────────────────────────────────────────────────── */
.testimonials {}

.testimonial-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 20px;
}

.testimonial-card {
  padding: 22px;
  border-radius: 18px;
  border: 1px solid var(--border);
  background: rgba(25,25,35,.7);
}

.testimonial-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 14px;
}

.testimonial-header h4 {
  font-size: 1rem;
  margin-bottom: 2px;
}

.testimonial-header span {
  color: var(--text-muted);
  font-size: 0.82rem;
}

.testimonial-card > p {
  color: var(--text-muted);
  font-size: 0.9rem;
  line-height: 1.6;
}

/* ─── Gallery ─────────────────────────────────────────────────────────────── */
.gallery-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 20px;
}

.gallery-tile {
  border-radius: 18px;
  border: 1px solid var(--border);
  overflow: hidden;
  background: #11111a;
}

.gallery-tile-img {
  height: 140px;
  width: 100%;
}

.gallery-tile > div {
  padding: 12px 14px 16px;
}

.gallery-tile span {
  display: block;
  font-size: 0.9rem;
  font-weight: 500;
  margin-bottom: 4px;
}

.gallery-tile small {
  color: var(--text-muted);
  font-size: 0.8rem;
}

/* ─── Powered by ──────────────────────────────────────────────────────────── */
.powered-by {}

.powered-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  justify-content: center;
}

.powered-badge {
  padding: 8px 18px;
  border-radius: 999px;
  border: 1px solid var(--border);
  background: var(--card);
  font-size: 0.88rem;
  color: var(--text-muted);
  white-space: nowrap;
}

/* ─── News ────────────────────────────────────────────────────────────────── */
.news-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 20px;
}

.news-card {
  padding: 22px;
  border-radius: 18px;
  border: 1px solid var(--border);
  background: var(--card);
}

.news-card a {
  font-weight: 600;
  font-size: 0.95rem;
  line-height: 1.5;
  display: block;
  color: var(--text);
  transition: color 0.2s;
}

.news-card a:hover {
  color: var(--accent);
}

.news-card span {
  display: block;
  margin-top: 14px;
  color: var(--text-muted);
  font-size: 0.85rem;
}

/* ─── FAQ ─────────────────────────────────────────────────────────────────── */
.faq-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 20px;
}

.faq-card {
  padding: 22px;
  border-radius: 18px;
  border: 1px solid var(--border);
  background: var(--card);
}

.faq-card h3 {
  margin-bottom: 12px;
  font-size: 1rem;
}

.faq-card p {
  color: var(--text-muted);
  font-size: 0.88rem;
  line-height: 1.6;
}

/* ─── Features / Capabilities ────────────────────────────────────────────── */
.free-tools {}

.tag-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 12px;
}

.tag-grid span {
  padding: 11px 16px;
  border-radius: 999px;
  border: 1px solid var(--border);
  background: var(--card);
  font-size: 0.88rem;
  color: var(--text-muted);
  text-align: center;
}

/* ─── Footer ──────────────────────────────────────────────────────────────── */
.site-footer {
  padding: 60px 0;
  border-top: 1px solid var(--border);
  background: #050508;
}

.footer-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 32px;
  color: var(--text-muted);
}

.footer-logo {
  font-size: 1.1rem;
  font-weight: 700;
  background: var(--accent-gradient);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  margin-bottom: 12px;
}

.footer-grid > div > p {
  font-size: 0.88rem;
  line-height: 1.6;
}

.footer-grid h4 {
  margin-bottom: 14px;
  color: var(--text);
  font-size: 0.95rem;
}

.footer-grid ul {
  list-style: none;
  display: grid;
  gap: 8px;
}

.footer-grid li {
  font-size: 0.88rem;
}

.footer-grid a {
  color: var(--text-muted);
  transition: color 0.2s;
}

.footer-grid a:hover {
  color: var(--accent);
}

/* ─── Mobile ──────────────────────────────────────────────────────────────── */
@media (max-width: 600px) {
  .nav-links {
    display: none;
  }

  .lang-label-text {
    display: none;
  }

  .carousel-btn {
    display: none;
  }
}
</style>
